package com.yanjinbin.model;

import java.io.Serializable;
import java.util.Date;

public class ArchiveAdditEntity implements Serializable {
    /**
     * 主键
     * 表字段 : archive_addit.id
     */
    private Long ArchiveAdditId;

    /**
     * 稿件id
     * 表字段 : archive_addit.aid
     */
    private Long aid;

    /**
     * 活动id
     * 表字段 : archive_addit.mission_id
     */
    private Integer missionId;

    /**
     * 稿件类型  0-ugc,1-pgc
     * 表字段 : archive_addit.up_from
     */
    private Byte upFrom;

    /**
     * 访问ip
     * 表字段 : archive_addit.from_ip
     */
    private Integer fromIp;

    /**
     * 创建时间
     * 表字段 : archive_addit.ctime
     */
    private Date ctime;

    /**
     * 修改时间
     * 表字段 : archive_addit.mtime
     */
    private Date mtime;

    /**
     * 跳转链接
     * 表字段 : archive_addit.redirect_url
     */
    private String redirectUrl;

    /**
     * 转载来源
     * 表字段 : archive_addit.source
     */
    private String source;

    /**
     * 商单id
     * 表字段 : archive_addit.order_id
     */
    private Integer orderId;

    /**
     * 私单类型:对应archive_config 中type为flow的id
     * 表字段 : archive_addit.flow_id
     */
    private Integer flowId;

    /**
     * 广告主,多个逗号分隔
     * 表字段 : archive_addit.advertiser
     */
    private String advertiser;

    /**
     * 私单自定义类型
     * 表字段 : archive_addit.flow_remark
     */
    private String flowRemark;

    /**
     * 完整的稿件简介
     * 表字段 : archive_addit.description
     */
    private String description;

    /**
     * 简介格式ID
     * 表字段 : archive_addit.desc_format_id
     */
    private Integer descFormatId;

    /**
     * 动态描述
     * 表字段 : archive_addit.dynamic
     */
    private String dynamic;

    /**
     * 稿件卡片
     * 表字段 : archive_addit.thumbnails
     */
    private String thumbnails;

    /**
     * 频道 id
     * 表字段 : archive_addit.channel_id
     */
    private Short channelId;

    /**
     * 回查原因
     * 表字段 : archive_addit.recheck_reason
     */
    private String recheckReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_addit
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:archive_addit.id
     *
     * @return archive_addit.id, 主键
     */
    public Long getArchiveAdditId() {
        return ArchiveAdditId;
    }

    /**
     * 设置 主键 字段:archive_addit.id
     *
     * @param ArchiveAdditId the value for archive_addit.id, 主键
     */
    public void setArchiveAdditId(Long ArchiveAdditId) {
        this.ArchiveAdditId = ArchiveAdditId;
    }

    /**
     * 获取 稿件id 字段:archive_addit.aid
     *
     * @return archive_addit.aid, 稿件id
     */
    public Long getAid() {
        return aid;
    }

    /**
     * 设置 稿件id 字段:archive_addit.aid
     *
     * @param aid the value for archive_addit.aid, 稿件id
     */
    public void setAid(Long aid) {
        this.aid = aid;
    }

    /**
     * 获取 活动id 字段:archive_addit.mission_id
     *
     * @return archive_addit.mission_id, 活动id
     */
    public Integer getMissionId() {
        return missionId;
    }

    /**
     * 设置 活动id 字段:archive_addit.mission_id
     *
     * @param missionId the value for archive_addit.mission_id, 活动id
     */
    public void setMissionId(Integer missionId) {
        this.missionId = missionId;
    }

    /**
     * 获取 稿件类型  0-ugc,1-pgc 字段:archive_addit.up_from
     *
     * @return archive_addit.up_from, 稿件类型  0-ugc,1-pgc
     */
    public Byte getUpFrom() {
        return upFrom;
    }

    /**
     * 设置 稿件类型  0-ugc,1-pgc 字段:archive_addit.up_from
     *
     * @param upFrom the value for archive_addit.up_from, 稿件类型  0-ugc,1-pgc
     */
    public void setUpFrom(Byte upFrom) {
        this.upFrom = upFrom;
    }

    /**
     * 获取 访问ip 字段:archive_addit.from_ip
     *
     * @return archive_addit.from_ip, 访问ip
     */
    public Integer getFromIp() {
        return fromIp;
    }

    /**
     * 设置 访问ip 字段:archive_addit.from_ip
     *
     * @param fromIp the value for archive_addit.from_ip, 访问ip
     */
    public void setFromIp(Integer fromIp) {
        this.fromIp = fromIp;
    }

    /**
     * 获取 创建时间 字段:archive_addit.ctime
     *
     * @return archive_addit.ctime, 创建时间
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * 设置 创建时间 字段:archive_addit.ctime
     *
     * @param ctime the value for archive_addit.ctime, 创建时间
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * 获取 修改时间 字段:archive_addit.mtime
     *
     * @return archive_addit.mtime, 修改时间
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * 设置 修改时间 字段:archive_addit.mtime
     *
     * @param mtime the value for archive_addit.mtime, 修改时间
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * 获取 跳转链接 字段:archive_addit.redirect_url
     *
     * @return archive_addit.redirect_url, 跳转链接
     */
    public String getRedirectUrl() {
        return redirectUrl;
    }

    /**
     * 设置 跳转链接 字段:archive_addit.redirect_url
     *
     * @param redirectUrl the value for archive_addit.redirect_url, 跳转链接
     */
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl == null ? null : redirectUrl.trim();
    }

    /**
     * 获取 转载来源 字段:archive_addit.source
     *
     * @return archive_addit.source, 转载来源
     */
    public String getSource() {
        return source;
    }

    /**
     * 设置 转载来源 字段:archive_addit.source
     *
     * @param source the value for archive_addit.source, 转载来源
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * 获取 商单id 字段:archive_addit.order_id
     *
     * @return archive_addit.order_id, 商单id
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * 设置 商单id 字段:archive_addit.order_id
     *
     * @param orderId the value for archive_addit.order_id, 商单id
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * 获取 私单类型:对应archive_config 中type为flow的id 字段:archive_addit.flow_id
     *
     * @return archive_addit.flow_id, 私单类型:对应archive_config 中type为flow的id
     */
    public Integer getFlowId() {
        return flowId;
    }

    /**
     * 设置 私单类型:对应archive_config 中type为flow的id 字段:archive_addit.flow_id
     *
     * @param flowId the value for archive_addit.flow_id, 私单类型:对应archive_config 中type为flow的id
     */
    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    /**
     * 获取 广告主,多个逗号分隔 字段:archive_addit.advertiser
     *
     * @return archive_addit.advertiser, 广告主,多个逗号分隔
     */
    public String getAdvertiser() {
        return advertiser;
    }

    /**
     * 设置 广告主,多个逗号分隔 字段:archive_addit.advertiser
     *
     * @param advertiser the value for archive_addit.advertiser, 广告主,多个逗号分隔
     */
    public void setAdvertiser(String advertiser) {
        this.advertiser = advertiser == null ? null : advertiser.trim();
    }

    /**
     * 获取 私单自定义类型 字段:archive_addit.flow_remark
     *
     * @return archive_addit.flow_remark, 私单自定义类型
     */
    public String getFlowRemark() {
        return flowRemark;
    }

    /**
     * 设置 私单自定义类型 字段:archive_addit.flow_remark
     *
     * @param flowRemark the value for archive_addit.flow_remark, 私单自定义类型
     */
    public void setFlowRemark(String flowRemark) {
        this.flowRemark = flowRemark == null ? null : flowRemark.trim();
    }

    /**
     * 获取 完整的稿件简介 字段:archive_addit.description
     *
     * @return archive_addit.description, 完整的稿件简介
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置 完整的稿件简介 字段:archive_addit.description
     *
     * @param description the value for archive_addit.description, 完整的稿件简介
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 获取 简介格式ID 字段:archive_addit.desc_format_id
     *
     * @return archive_addit.desc_format_id, 简介格式ID
     */
    public Integer getDescFormatId() {
        return descFormatId;
    }

    /**
     * 设置 简介格式ID 字段:archive_addit.desc_format_id
     *
     * @param descFormatId the value for archive_addit.desc_format_id, 简介格式ID
     */
    public void setDescFormatId(Integer descFormatId) {
        this.descFormatId = descFormatId;
    }

    /**
     * 获取 动态描述 字段:archive_addit.dynamic
     *
     * @return archive_addit.dynamic, 动态描述
     */
    public String getDynamic() {
        return dynamic;
    }

    /**
     * 设置 动态描述 字段:archive_addit.dynamic
     *
     * @param dynamic the value for archive_addit.dynamic, 动态描述
     */
    public void setDynamic(String dynamic) {
        this.dynamic = dynamic == null ? null : dynamic.trim();
    }

    /**
     * 获取 稿件卡片 字段:archive_addit.thumbnails
     *
     * @return archive_addit.thumbnails, 稿件卡片
     */
    public String getThumbnails() {
        return thumbnails;
    }

    /**
     * 设置 稿件卡片 字段:archive_addit.thumbnails
     *
     * @param thumbnails the value for archive_addit.thumbnails, 稿件卡片
     */
    public void setThumbnails(String thumbnails) {
        this.thumbnails = thumbnails == null ? null : thumbnails.trim();
    }

    /**
     * 获取 频道 id 字段:archive_addit.channel_id
     *
     * @return archive_addit.channel_id, 频道 id
     */
    public Short getChannelId() {
        return channelId;
    }

    /**
     * 设置 频道 id 字段:archive_addit.channel_id
     *
     * @param channelId the value for archive_addit.channel_id, 频道 id
     */
    public void setChannelId(Short channelId) {
        this.channelId = channelId;
    }

    /**
     * 获取 回查原因 字段:archive_addit.recheck_reason
     *
     * @return archive_addit.recheck_reason, 回查原因
     */
    public String getRecheckReason() {
        return recheckReason;
    }

    /**
     * 设置 回查原因 字段:archive_addit.recheck_reason
     *
     * @param recheckReason the value for archive_addit.recheck_reason, 回查原因
     */
    public void setRecheckReason(String recheckReason) {
        this.recheckReason = recheckReason == null ? null : recheckReason.trim();
    }

    /**
     * ,archive_addit
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ArchiveAdditId=").append(ArchiveAdditId);
        sb.append(", aid=").append(aid);
        sb.append(", missionId=").append(missionId);
        sb.append(", upFrom=").append(upFrom);
        sb.append(", fromIp=").append(fromIp);
        sb.append(", ctime=").append(ctime);
        sb.append(", mtime=").append(mtime);
        sb.append(", redirectUrl=").append(redirectUrl);
        sb.append(", source=").append(source);
        sb.append(", orderId=").append(orderId);
        sb.append(", flowId=").append(flowId);
        sb.append(", advertiser=").append(advertiser);
        sb.append(", flowRemark=").append(flowRemark);
        sb.append(", description=").append(description);
        sb.append(", descFormatId=").append(descFormatId);
        sb.append(", dynamic=").append(dynamic);
        sb.append(", thumbnails=").append(thumbnails);
        sb.append(", channelId=").append(channelId);
        sb.append(", recheckReason=").append(recheckReason);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}