package com.yanjinbin.model;

import java.io.Serializable;
import java.util.Date;

public class ArchiveStatEntity implements Serializable {
    /**
     * 主键
     * 表字段 : archive_stat.id
     */
    private Long ArchiveStatId;

    /**
     * 稿件生产日期
     * 表字段 : archive_stat.log_date
     */
    private Date logDate;

    /**
     * 稿件来源
     * 表字段 : archive_stat.up_from
     */
    private Byte upFrom;

    /**
     * 稿件生产阶段ID
     * 表字段 : archive_stat.archive_stage_id
     */
    private Byte archiveStageId;

    /**
     * 创建时间
     * 表字段 : archive_stat.ctime
     */
    private Date ctime;

    /**
     * 修改时间
     * 表字段 : archive_stat.mtime
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_stat
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:archive_stat.id
     *
     * @return archive_stat.id, 主键
     */
    public Long getArchiveStatId() {
        return ArchiveStatId;
    }

    /**
     * 设置 主键 字段:archive_stat.id
     *
     * @param ArchiveStatId the value for archive_stat.id, 主键
     */
    public void setArchiveStatId(Long ArchiveStatId) {
        this.ArchiveStatId = ArchiveStatId;
    }

    /**
     * 获取 稿件生产日期 字段:archive_stat.log_date
     *
     * @return archive_stat.log_date, 稿件生产日期
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * 设置 稿件生产日期 字段:archive_stat.log_date
     *
     * @param logDate the value for archive_stat.log_date, 稿件生产日期
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * 获取 稿件来源 字段:archive_stat.up_from
     *
     * @return archive_stat.up_from, 稿件来源
     */
    public Byte getUpFrom() {
        return upFrom;
    }

    /**
     * 设置 稿件来源 字段:archive_stat.up_from
     *
     * @param upFrom the value for archive_stat.up_from, 稿件来源
     */
    public void setUpFrom(Byte upFrom) {
        this.upFrom = upFrom;
    }

    /**
     * 获取 稿件生产阶段ID 字段:archive_stat.archive_stage_id
     *
     * @return archive_stat.archive_stage_id, 稿件生产阶段ID
     */
    public Byte getArchiveStageId() {
        return archiveStageId;
    }

    /**
     * 设置 稿件生产阶段ID 字段:archive_stat.archive_stage_id
     *
     * @param archiveStageId the value for archive_stat.archive_stage_id, 稿件生产阶段ID
     */
    public void setArchiveStageId(Byte archiveStageId) {
        this.archiveStageId = archiveStageId;
    }

    /**
     * 获取 创建时间 字段:archive_stat.ctime
     *
     * @return archive_stat.ctime, 创建时间
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * 设置 创建时间 字段:archive_stat.ctime
     *
     * @param ctime the value for archive_stat.ctime, 创建时间
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * 获取 修改时间 字段:archive_stat.mtime
     *
     * @return archive_stat.mtime, 修改时间
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * 设置 修改时间 字段:archive_stat.mtime
     *
     * @param mtime the value for archive_stat.mtime, 修改时间
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * ,archive_stat
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ArchiveStatId=").append(ArchiveStatId);
        sb.append(", logDate=").append(logDate);
        sb.append(", upFrom=").append(upFrom);
        sb.append(", archiveStageId=").append(archiveStageId);
        sb.append(", ctime=").append(ctime);
        sb.append(", mtime=").append(mtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}