package com.yanjinbin.model;

import java.io.Serializable;
import java.util.Date;

public class ArchiveVideoRelationEntity implements Serializable {
    /**
     * 主键ID
     * 表字段 : archive_video_relation.id
     */
    private Long ArchiveVideoRelationId;

    /**
     * 稿件ID
     * 表字段 : archive_video_relation.aid
     */
    private Long aid;

    /**
     * 视频CID
     * 表字段 : archive_video_relation.cid
     */
    private Long cid;

    /**
     * 分P标题
     * 表字段 : archive_video_relation.title
     */
    private String title;

    /**
     * 分P简介
     * 表字段 : archive_video_relation.description
     */
    private String description;

    /**
     * 分批顺序
     * 表字段 : archive_video_relation.index_order
     */
    private Integer indexOrder;

    /**
     * 创建时间
     * 表字段 : archive_video_relation.ctime
     */
    private Date ctime;

    /**
     * 更新时间
     * 表字段 : archive_video_relation.mtime
     */
    private Date mtime;

    /**
     * 稿件视频关联状态：0-正常,-100-删除
     * 表字段 : archive_video_relation.state
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_video_relation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键ID 字段:archive_video_relation.id
     *
     * @return archive_video_relation.id, 主键ID
     */
    public Long getArchiveVideoRelationId() {
        return ArchiveVideoRelationId;
    }

    /**
     * 设置 主键ID 字段:archive_video_relation.id
     *
     * @param ArchiveVideoRelationId the value for archive_video_relation.id, 主键ID
     */
    public void setArchiveVideoRelationId(Long ArchiveVideoRelationId) {
        this.ArchiveVideoRelationId = ArchiveVideoRelationId;
    }

    /**
     * 获取 稿件ID 字段:archive_video_relation.aid
     *
     * @return archive_video_relation.aid, 稿件ID
     */
    public Long getAid() {
        return aid;
    }

    /**
     * 设置 稿件ID 字段:archive_video_relation.aid
     *
     * @param aid the value for archive_video_relation.aid, 稿件ID
     */
    public void setAid(Long aid) {
        this.aid = aid;
    }

    /**
     * 获取 视频CID 字段:archive_video_relation.cid
     *
     * @return archive_video_relation.cid, 视频CID
     */
    public Long getCid() {
        return cid;
    }

    /**
     * 设置 视频CID 字段:archive_video_relation.cid
     *
     * @param cid the value for archive_video_relation.cid, 视频CID
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * 获取 分P标题 字段:archive_video_relation.title
     *
     * @return archive_video_relation.title, 分P标题
     */
    public String getTitle() {
        return title;
    }

    /**
     * 设置 分P标题 字段:archive_video_relation.title
     *
     * @param title the value for archive_video_relation.title, 分P标题
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 获取 分P简介 字段:archive_video_relation.description
     *
     * @return archive_video_relation.description, 分P简介
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置 分P简介 字段:archive_video_relation.description
     *
     * @param description the value for archive_video_relation.description, 分P简介
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 获取 分批顺序 字段:archive_video_relation.index_order
     *
     * @return archive_video_relation.index_order, 分批顺序
     */
    public Integer getIndexOrder() {
        return indexOrder;
    }

    /**
     * 设置 分批顺序 字段:archive_video_relation.index_order
     *
     * @param indexOrder the value for archive_video_relation.index_order, 分批顺序
     */
    public void setIndexOrder(Integer indexOrder) {
        this.indexOrder = indexOrder;
    }

    /**
     * 获取 创建时间 字段:archive_video_relation.ctime
     *
     * @return archive_video_relation.ctime, 创建时间
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * 设置 创建时间 字段:archive_video_relation.ctime
     *
     * @param ctime the value for archive_video_relation.ctime, 创建时间
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * 获取 更新时间 字段:archive_video_relation.mtime
     *
     * @return archive_video_relation.mtime, 更新时间
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * 设置 更新时间 字段:archive_video_relation.mtime
     *
     * @param mtime the value for archive_video_relation.mtime, 更新时间
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * 获取 稿件视频关联状态：0-正常,-100-删除 字段:archive_video_relation.state
     *
     * @return archive_video_relation.state, 稿件视频关联状态：0-正常,-100-删除
     */
    public Byte getState() {
        return state;
    }

    /**
     * 设置 稿件视频关联状态：0-正常,-100-删除 字段:archive_video_relation.state
     *
     * @param state the value for archive_video_relation.state, 稿件视频关联状态：0-正常,-100-删除
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * ,archive_video_relation
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ArchiveVideoRelationId=").append(ArchiveVideoRelationId);
        sb.append(", aid=").append(aid);
        sb.append(", cid=").append(cid);
        sb.append(", title=").append(title);
        sb.append(", description=").append(description);
        sb.append(", indexOrder=").append(indexOrder);
        sb.append(", ctime=").append(ctime);
        sb.append(", mtime=").append(mtime);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}