package com.yanjinbin.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArchiveAdditEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_addit
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_addit
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_addit
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    protected Integer limit;

    protected Integer offset;

    /**
     *  构造查询条件,archive_addit
     */
    public ArchiveAdditEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,archive_addit
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,archive_addit
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,archive_addit
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,archive_addit
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,archive_addit
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,archive_addit
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,archive_addit
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,archive_addit
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,archive_addit
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,archive_addit
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        offset = null;
        limit = null;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return this.limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public ArchiveAdditEntityExample limit(Integer offset) {
        this.offset = offset;
        return this;
    }

    public ArchiveAdditEntityExample limit(Integer limit, Integer offset) {
        this.limit = limit;
        this.offset = offset;
        return this;
    }

    public ArchiveAdditEntityExample page(Integer page, Integer pageSize) {
        this.limit = page * pageSize;
        this.offset = pageSize;
        return this;
    }

    /**
     * archive_addit
     * GeneratedCriteria
     * 数据库表：archive_addit
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andArchiveAdditIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andArchiveAdditIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andArchiveAdditIdEqualTo(Long value) {
            addCriterion("id =", value, "ArchiveAdditId");
            return (Criteria) this;
        }

        public Criteria andArchiveAdditIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "ArchiveAdditId");
            return (Criteria) this;
        }

        public Criteria andArchiveAdditIdGreaterThan(Long value) {
            addCriterion("id >", value, "ArchiveAdditId");
            return (Criteria) this;
        }

        public Criteria andArchiveAdditIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "ArchiveAdditId");
            return (Criteria) this;
        }

        public Criteria andArchiveAdditIdLessThan(Long value) {
            addCriterion("id <", value, "ArchiveAdditId");
            return (Criteria) this;
        }

        public Criteria andArchiveAdditIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "ArchiveAdditId");
            return (Criteria) this;
        }

        public Criteria andArchiveAdditIdIn(List<Long> values) {
            addCriterion("id in", values, "ArchiveAdditId");
            return (Criteria) this;
        }

        public Criteria andArchiveAdditIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "ArchiveAdditId");
            return (Criteria) this;
        }

        public Criteria andArchiveAdditIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "ArchiveAdditId");
            return (Criteria) this;
        }

        public Criteria andArchiveAdditIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "ArchiveAdditId");
            return (Criteria) this;
        }

        public Criteria andAidIsNull() {
            addCriterion("aid is null");
            return (Criteria) this;
        }

        public Criteria andAidIsNotNull() {
            addCriterion("aid is not null");
            return (Criteria) this;
        }

        public Criteria andAidEqualTo(Long value) {
            addCriterion("aid =", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotEqualTo(Long value) {
            addCriterion("aid <>", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThan(Long value) {
            addCriterion("aid >", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThanOrEqualTo(Long value) {
            addCriterion("aid >=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThan(Long value) {
            addCriterion("aid <", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThanOrEqualTo(Long value) {
            addCriterion("aid <=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidIn(List<Long> values) {
            addCriterion("aid in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotIn(List<Long> values) {
            addCriterion("aid not in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidBetween(Long value1, Long value2) {
            addCriterion("aid between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotBetween(Long value1, Long value2) {
            addCriterion("aid not between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andMissionIdIsNull() {
            addCriterion("mission_id is null");
            return (Criteria) this;
        }

        public Criteria andMissionIdIsNotNull() {
            addCriterion("mission_id is not null");
            return (Criteria) this;
        }

        public Criteria andMissionIdEqualTo(Integer value) {
            addCriterion("mission_id =", value, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdNotEqualTo(Integer value) {
            addCriterion("mission_id <>", value, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdGreaterThan(Integer value) {
            addCriterion("mission_id >", value, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mission_id >=", value, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdLessThan(Integer value) {
            addCriterion("mission_id <", value, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdLessThanOrEqualTo(Integer value) {
            addCriterion("mission_id <=", value, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdIn(List<Integer> values) {
            addCriterion("mission_id in", values, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdNotIn(List<Integer> values) {
            addCriterion("mission_id not in", values, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdBetween(Integer value1, Integer value2) {
            addCriterion("mission_id between", value1, value2, "missionId");
            return (Criteria) this;
        }

        public Criteria andMissionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mission_id not between", value1, value2, "missionId");
            return (Criteria) this;
        }

        public Criteria andUpFromIsNull() {
            addCriterion("up_from is null");
            return (Criteria) this;
        }

        public Criteria andUpFromIsNotNull() {
            addCriterion("up_from is not null");
            return (Criteria) this;
        }

        public Criteria andUpFromEqualTo(Byte value) {
            addCriterion("up_from =", value, "upFrom");
            return (Criteria) this;
        }

        public Criteria andUpFromNotEqualTo(Byte value) {
            addCriterion("up_from <>", value, "upFrom");
            return (Criteria) this;
        }

        public Criteria andUpFromGreaterThan(Byte value) {
            addCriterion("up_from >", value, "upFrom");
            return (Criteria) this;
        }

        public Criteria andUpFromGreaterThanOrEqualTo(Byte value) {
            addCriterion("up_from >=", value, "upFrom");
            return (Criteria) this;
        }

        public Criteria andUpFromLessThan(Byte value) {
            addCriterion("up_from <", value, "upFrom");
            return (Criteria) this;
        }

        public Criteria andUpFromLessThanOrEqualTo(Byte value) {
            addCriterion("up_from <=", value, "upFrom");
            return (Criteria) this;
        }

        public Criteria andUpFromIn(List<Byte> values) {
            addCriterion("up_from in", values, "upFrom");
            return (Criteria) this;
        }

        public Criteria andUpFromNotIn(List<Byte> values) {
            addCriterion("up_from not in", values, "upFrom");
            return (Criteria) this;
        }

        public Criteria andUpFromBetween(Byte value1, Byte value2) {
            addCriterion("up_from between", value1, value2, "upFrom");
            return (Criteria) this;
        }

        public Criteria andUpFromNotBetween(Byte value1, Byte value2) {
            addCriterion("up_from not between", value1, value2, "upFrom");
            return (Criteria) this;
        }

        public Criteria andFromIpIsNull() {
            addCriterion("from_ip is null");
            return (Criteria) this;
        }

        public Criteria andFromIpIsNotNull() {
            addCriterion("from_ip is not null");
            return (Criteria) this;
        }

        public Criteria andFromIpEqualTo(Integer value) {
            addCriterion("from_ip =", value, "fromIp");
            return (Criteria) this;
        }

        public Criteria andFromIpNotEqualTo(Integer value) {
            addCriterion("from_ip <>", value, "fromIp");
            return (Criteria) this;
        }

        public Criteria andFromIpGreaterThan(Integer value) {
            addCriterion("from_ip >", value, "fromIp");
            return (Criteria) this;
        }

        public Criteria andFromIpGreaterThanOrEqualTo(Integer value) {
            addCriterion("from_ip >=", value, "fromIp");
            return (Criteria) this;
        }

        public Criteria andFromIpLessThan(Integer value) {
            addCriterion("from_ip <", value, "fromIp");
            return (Criteria) this;
        }

        public Criteria andFromIpLessThanOrEqualTo(Integer value) {
            addCriterion("from_ip <=", value, "fromIp");
            return (Criteria) this;
        }

        public Criteria andFromIpIn(List<Integer> values) {
            addCriterion("from_ip in", values, "fromIp");
            return (Criteria) this;
        }

        public Criteria andFromIpNotIn(List<Integer> values) {
            addCriterion("from_ip not in", values, "fromIp");
            return (Criteria) this;
        }

        public Criteria andFromIpBetween(Integer value1, Integer value2) {
            addCriterion("from_ip between", value1, value2, "fromIp");
            return (Criteria) this;
        }

        public Criteria andFromIpNotBetween(Integer value1, Integer value2) {
            addCriterion("from_ip not between", value1, value2, "fromIp");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(Date value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(Date value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(Date value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(Date value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(Date value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<Date> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<Date> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(Date value1, Date value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(Date value1, Date value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlIsNull() {
            addCriterion("redirect_url is null");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlIsNotNull() {
            addCriterion("redirect_url is not null");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlEqualTo(String value) {
            addCriterion("redirect_url =", value, "redirectUrl");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlNotEqualTo(String value) {
            addCriterion("redirect_url <>", value, "redirectUrl");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlGreaterThan(String value) {
            addCriterion("redirect_url >", value, "redirectUrl");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlGreaterThanOrEqualTo(String value) {
            addCriterion("redirect_url >=", value, "redirectUrl");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlLessThan(String value) {
            addCriterion("redirect_url <", value, "redirectUrl");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlLessThanOrEqualTo(String value) {
            addCriterion("redirect_url <=", value, "redirectUrl");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlLike(String value) {
            addCriterion("redirect_url like", value, "redirectUrl");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlNotLike(String value) {
            addCriterion("redirect_url not like", value, "redirectUrl");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlIn(List<String> values) {
            addCriterion("redirect_url in", values, "redirectUrl");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlNotIn(List<String> values) {
            addCriterion("redirect_url not in", values, "redirectUrl");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlBetween(String value1, String value2) {
            addCriterion("redirect_url between", value1, value2, "redirectUrl");
            return (Criteria) this;
        }

        public Criteria andRedirectUrlNotBetween(String value1, String value2) {
            addCriterion("redirect_url not between", value1, value2, "redirectUrl");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("`source` is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("`source` is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("`source` =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("`source` <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("`source` >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("`source` >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("`source` <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("`source` <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("`source` like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("`source` not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("`source` in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("`source` not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("`source` between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("`source` not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andFlowIdIsNull() {
            addCriterion("flow_id is null");
            return (Criteria) this;
        }

        public Criteria andFlowIdIsNotNull() {
            addCriterion("flow_id is not null");
            return (Criteria) this;
        }

        public Criteria andFlowIdEqualTo(Integer value) {
            addCriterion("flow_id =", value, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdNotEqualTo(Integer value) {
            addCriterion("flow_id <>", value, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdGreaterThan(Integer value) {
            addCriterion("flow_id >", value, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("flow_id >=", value, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdLessThan(Integer value) {
            addCriterion("flow_id <", value, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdLessThanOrEqualTo(Integer value) {
            addCriterion("flow_id <=", value, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdIn(List<Integer> values) {
            addCriterion("flow_id in", values, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdNotIn(List<Integer> values) {
            addCriterion("flow_id not in", values, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdBetween(Integer value1, Integer value2) {
            addCriterion("flow_id between", value1, value2, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdNotBetween(Integer value1, Integer value2) {
            addCriterion("flow_id not between", value1, value2, "flowId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIsNull() {
            addCriterion("advertiser is null");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIsNotNull() {
            addCriterion("advertiser is not null");
            return (Criteria) this;
        }

        public Criteria andAdvertiserEqualTo(String value) {
            addCriterion("advertiser =", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserNotEqualTo(String value) {
            addCriterion("advertiser <>", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserGreaterThan(String value) {
            addCriterion("advertiser >", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserGreaterThanOrEqualTo(String value) {
            addCriterion("advertiser >=", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserLessThan(String value) {
            addCriterion("advertiser <", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserLessThanOrEqualTo(String value) {
            addCriterion("advertiser <=", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserLike(String value) {
            addCriterion("advertiser like", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserNotLike(String value) {
            addCriterion("advertiser not like", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIn(List<String> values) {
            addCriterion("advertiser in", values, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserNotIn(List<String> values) {
            addCriterion("advertiser not in", values, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserBetween(String value1, String value2) {
            addCriterion("advertiser between", value1, value2, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserNotBetween(String value1, String value2) {
            addCriterion("advertiser not between", value1, value2, "advertiser");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkIsNull() {
            addCriterion("flow_remark is null");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkIsNotNull() {
            addCriterion("flow_remark is not null");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkEqualTo(String value) {
            addCriterion("flow_remark =", value, "flowRemark");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkNotEqualTo(String value) {
            addCriterion("flow_remark <>", value, "flowRemark");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkGreaterThan(String value) {
            addCriterion("flow_remark >", value, "flowRemark");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("flow_remark >=", value, "flowRemark");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkLessThan(String value) {
            addCriterion("flow_remark <", value, "flowRemark");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkLessThanOrEqualTo(String value) {
            addCriterion("flow_remark <=", value, "flowRemark");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkLike(String value) {
            addCriterion("flow_remark like", value, "flowRemark");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkNotLike(String value) {
            addCriterion("flow_remark not like", value, "flowRemark");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkIn(List<String> values) {
            addCriterion("flow_remark in", values, "flowRemark");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkNotIn(List<String> values) {
            addCriterion("flow_remark not in", values, "flowRemark");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkBetween(String value1, String value2) {
            addCriterion("flow_remark between", value1, value2, "flowRemark");
            return (Criteria) this;
        }

        public Criteria andFlowRemarkNotBetween(String value1, String value2) {
            addCriterion("flow_remark not between", value1, value2, "flowRemark");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescFormatIdIsNull() {
            addCriterion("desc_format_id is null");
            return (Criteria) this;
        }

        public Criteria andDescFormatIdIsNotNull() {
            addCriterion("desc_format_id is not null");
            return (Criteria) this;
        }

        public Criteria andDescFormatIdEqualTo(Integer value) {
            addCriterion("desc_format_id =", value, "descFormatId");
            return (Criteria) this;
        }

        public Criteria andDescFormatIdNotEqualTo(Integer value) {
            addCriterion("desc_format_id <>", value, "descFormatId");
            return (Criteria) this;
        }

        public Criteria andDescFormatIdGreaterThan(Integer value) {
            addCriterion("desc_format_id >", value, "descFormatId");
            return (Criteria) this;
        }

        public Criteria andDescFormatIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("desc_format_id >=", value, "descFormatId");
            return (Criteria) this;
        }

        public Criteria andDescFormatIdLessThan(Integer value) {
            addCriterion("desc_format_id <", value, "descFormatId");
            return (Criteria) this;
        }

        public Criteria andDescFormatIdLessThanOrEqualTo(Integer value) {
            addCriterion("desc_format_id <=", value, "descFormatId");
            return (Criteria) this;
        }

        public Criteria andDescFormatIdIn(List<Integer> values) {
            addCriterion("desc_format_id in", values, "descFormatId");
            return (Criteria) this;
        }

        public Criteria andDescFormatIdNotIn(List<Integer> values) {
            addCriterion("desc_format_id not in", values, "descFormatId");
            return (Criteria) this;
        }

        public Criteria andDescFormatIdBetween(Integer value1, Integer value2) {
            addCriterion("desc_format_id between", value1, value2, "descFormatId");
            return (Criteria) this;
        }

        public Criteria andDescFormatIdNotBetween(Integer value1, Integer value2) {
            addCriterion("desc_format_id not between", value1, value2, "descFormatId");
            return (Criteria) this;
        }

        public Criteria andDynamicIsNull() {
            addCriterion("`dynamic` is null");
            return (Criteria) this;
        }

        public Criteria andDynamicIsNotNull() {
            addCriterion("`dynamic` is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicEqualTo(String value) {
            addCriterion("`dynamic` =", value, "dynamic");
            return (Criteria) this;
        }

        public Criteria andDynamicNotEqualTo(String value) {
            addCriterion("`dynamic` <>", value, "dynamic");
            return (Criteria) this;
        }

        public Criteria andDynamicGreaterThan(String value) {
            addCriterion("`dynamic` >", value, "dynamic");
            return (Criteria) this;
        }

        public Criteria andDynamicGreaterThanOrEqualTo(String value) {
            addCriterion("`dynamic` >=", value, "dynamic");
            return (Criteria) this;
        }

        public Criteria andDynamicLessThan(String value) {
            addCriterion("`dynamic` <", value, "dynamic");
            return (Criteria) this;
        }

        public Criteria andDynamicLessThanOrEqualTo(String value) {
            addCriterion("`dynamic` <=", value, "dynamic");
            return (Criteria) this;
        }

        public Criteria andDynamicLike(String value) {
            addCriterion("`dynamic` like", value, "dynamic");
            return (Criteria) this;
        }

        public Criteria andDynamicNotLike(String value) {
            addCriterion("`dynamic` not like", value, "dynamic");
            return (Criteria) this;
        }

        public Criteria andDynamicIn(List<String> values) {
            addCriterion("`dynamic` in", values, "dynamic");
            return (Criteria) this;
        }

        public Criteria andDynamicNotIn(List<String> values) {
            addCriterion("`dynamic` not in", values, "dynamic");
            return (Criteria) this;
        }

        public Criteria andDynamicBetween(String value1, String value2) {
            addCriterion("`dynamic` between", value1, value2, "dynamic");
            return (Criteria) this;
        }

        public Criteria andDynamicNotBetween(String value1, String value2) {
            addCriterion("`dynamic` not between", value1, value2, "dynamic");
            return (Criteria) this;
        }

        public Criteria andThumbnailsIsNull() {
            addCriterion("thumbnails is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailsIsNotNull() {
            addCriterion("thumbnails is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailsEqualTo(String value) {
            addCriterion("thumbnails =", value, "thumbnails");
            return (Criteria) this;
        }

        public Criteria andThumbnailsNotEqualTo(String value) {
            addCriterion("thumbnails <>", value, "thumbnails");
            return (Criteria) this;
        }

        public Criteria andThumbnailsGreaterThan(String value) {
            addCriterion("thumbnails >", value, "thumbnails");
            return (Criteria) this;
        }

        public Criteria andThumbnailsGreaterThanOrEqualTo(String value) {
            addCriterion("thumbnails >=", value, "thumbnails");
            return (Criteria) this;
        }

        public Criteria andThumbnailsLessThan(String value) {
            addCriterion("thumbnails <", value, "thumbnails");
            return (Criteria) this;
        }

        public Criteria andThumbnailsLessThanOrEqualTo(String value) {
            addCriterion("thumbnails <=", value, "thumbnails");
            return (Criteria) this;
        }

        public Criteria andThumbnailsLike(String value) {
            addCriterion("thumbnails like", value, "thumbnails");
            return (Criteria) this;
        }

        public Criteria andThumbnailsNotLike(String value) {
            addCriterion("thumbnails not like", value, "thumbnails");
            return (Criteria) this;
        }

        public Criteria andThumbnailsIn(List<String> values) {
            addCriterion("thumbnails in", values, "thumbnails");
            return (Criteria) this;
        }

        public Criteria andThumbnailsNotIn(List<String> values) {
            addCriterion("thumbnails not in", values, "thumbnails");
            return (Criteria) this;
        }

        public Criteria andThumbnailsBetween(String value1, String value2) {
            addCriterion("thumbnails between", value1, value2, "thumbnails");
            return (Criteria) this;
        }

        public Criteria andThumbnailsNotBetween(String value1, String value2) {
            addCriterion("thumbnails not between", value1, value2, "thumbnails");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("channel_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(Short value) {
            addCriterion("channel_id =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(Short value) {
            addCriterion("channel_id <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(Short value) {
            addCriterion("channel_id >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(Short value) {
            addCriterion("channel_id >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(Short value) {
            addCriterion("channel_id <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(Short value) {
            addCriterion("channel_id <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<Short> values) {
            addCriterion("channel_id in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<Short> values) {
            addCriterion("channel_id not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(Short value1, Short value2) {
            addCriterion("channel_id between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(Short value1, Short value2) {
            addCriterion("channel_id not between", value1, value2, "channelId");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：archive_addit
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * archive_addit
     * Criterion
     * 数据库表：archive_addit
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}