package com.yanjinbin.model;

import java.io.Serializable;
import java.util.Date;

public class ArchiveStageConfEntity implements Serializable {
    /**
     * 主键
     * 表字段 : archive_stage_conf.id
     */
    private Long ArchiveStageConfId;

    /**
     * 稿件阶段名字
     * 表字段 : archive_stage_conf.stage_name
     */
    private String stageName;

    /**
     * 稿件阶段值
     * 表字段 : archive_stage_conf.stage_value
     */
    private Byte stageValue;

    /**
     * 创建时间
     * 表字段 : archive_stage_conf.ctime
     */
    private Date ctime;

    /**
     * 修改时间
     * 表字段 : archive_stage_conf.mtime
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_stage_conf
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:archive_stage_conf.id
     *
     * @return archive_stage_conf.id, 主键
     */
    public Long getArchiveStageConfId() {
        return ArchiveStageConfId;
    }

    /**
     * 设置 主键 字段:archive_stage_conf.id
     *
     * @param ArchiveStageConfId the value for archive_stage_conf.id, 主键
     */
    public void setArchiveStageConfId(Long ArchiveStageConfId) {
        this.ArchiveStageConfId = ArchiveStageConfId;
    }

    /**
     * 获取 稿件阶段名字 字段:archive_stage_conf.stage_name
     *
     * @return archive_stage_conf.stage_name, 稿件阶段名字
     */
    public String getStageName() {
        return stageName;
    }

    /**
     * 设置 稿件阶段名字 字段:archive_stage_conf.stage_name
     *
     * @param stageName the value for archive_stage_conf.stage_name, 稿件阶段名字
     */
    public void setStageName(String stageName) {
        this.stageName = stageName == null ? null : stageName.trim();
    }

    /**
     * 获取 稿件阶段值 字段:archive_stage_conf.stage_value
     *
     * @return archive_stage_conf.stage_value, 稿件阶段值
     */
    public Byte getStageValue() {
        return stageValue;
    }

    /**
     * 设置 稿件阶段值 字段:archive_stage_conf.stage_value
     *
     * @param stageValue the value for archive_stage_conf.stage_value, 稿件阶段值
     */
    public void setStageValue(Byte stageValue) {
        this.stageValue = stageValue;
    }

    /**
     * 获取 创建时间 字段:archive_stage_conf.ctime
     *
     * @return archive_stage_conf.ctime, 创建时间
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * 设置 创建时间 字段:archive_stage_conf.ctime
     *
     * @param ctime the value for archive_stage_conf.ctime, 创建时间
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * 获取 修改时间 字段:archive_stage_conf.mtime
     *
     * @return archive_stage_conf.mtime, 修改时间
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * 设置 修改时间 字段:archive_stage_conf.mtime
     *
     * @param mtime the value for archive_stage_conf.mtime, 修改时间
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * ,archive_stage_conf
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ArchiveStageConfId=").append(ArchiveStageConfId);
        sb.append(", stageName=").append(stageName);
        sb.append(", stageValue=").append(stageValue);
        sb.append(", ctime=").append(ctime);
        sb.append(", mtime=").append(mtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}