package com.yanjinbin.model;

import java.io.Serializable;
import java.util.Date;

public class ArchiveVideoTrackEntity implements Serializable {
    /**
     * 自增ID
     * 表字段 : archive_video_track.id
     */
    private Integer ArchiveVideoTrackId;

    /**
     * 稿件ID
     * 表字段 : archive_video_track.aid
     */
    private Integer aid;

    /**
     * 分P文件hash
     * 表字段 : archive_video_track.filename
     */
    private String filename;

    /**
     * 视频审核状态
     * 表字段 : archive_video_track.status
     */
    private Byte status;

    /**
     * 视频转码状态
     * 表字段 : archive_video_track.xcode_state
     */
    private Byte xcodeState;

    /**
     * 创建时间
     * 表字段 : archive_video_track.ctime
     */
    private Date ctime;

    /**
     * 修改时间
     * 表字段 : archive_video_track.mtime
     */
    private Date mtime;

    /**
     * 其他信息
     * 表字段 : archive_video_track.remark
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_video_track
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 自增ID 字段:archive_video_track.id
     *
     * @return archive_video_track.id, 自增ID
     */
    public Integer getArchiveVideoTrackId() {
        return ArchiveVideoTrackId;
    }

    /**
     * 设置 自增ID 字段:archive_video_track.id
     *
     * @param ArchiveVideoTrackId the value for archive_video_track.id, 自增ID
     */
    public void setArchiveVideoTrackId(Integer ArchiveVideoTrackId) {
        this.ArchiveVideoTrackId = ArchiveVideoTrackId;
    }

    /**
     * 获取 稿件ID 字段:archive_video_track.aid
     *
     * @return archive_video_track.aid, 稿件ID
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * 设置 稿件ID 字段:archive_video_track.aid
     *
     * @param aid the value for archive_video_track.aid, 稿件ID
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * 获取 分P文件hash 字段:archive_video_track.filename
     *
     * @return archive_video_track.filename, 分P文件hash
     */
    public String getFilename() {
        return filename;
    }

    /**
     * 设置 分P文件hash 字段:archive_video_track.filename
     *
     * @param filename the value for archive_video_track.filename, 分P文件hash
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * 获取 视频审核状态 字段:archive_video_track.status
     *
     * @return archive_video_track.status, 视频审核状态
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 设置 视频审核状态 字段:archive_video_track.status
     *
     * @param status the value for archive_video_track.status, 视频审核状态
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 获取 视频转码状态 字段:archive_video_track.xcode_state
     *
     * @return archive_video_track.xcode_state, 视频转码状态
     */
    public Byte getXcodeState() {
        return xcodeState;
    }

    /**
     * 设置 视频转码状态 字段:archive_video_track.xcode_state
     *
     * @param xcodeState the value for archive_video_track.xcode_state, 视频转码状态
     */
    public void setXcodeState(Byte xcodeState) {
        this.xcodeState = xcodeState;
    }

    /**
     * 获取 创建时间 字段:archive_video_track.ctime
     *
     * @return archive_video_track.ctime, 创建时间
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * 设置 创建时间 字段:archive_video_track.ctime
     *
     * @param ctime the value for archive_video_track.ctime, 创建时间
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * 获取 修改时间 字段:archive_video_track.mtime
     *
     * @return archive_video_track.mtime, 修改时间
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * 设置 修改时间 字段:archive_video_track.mtime
     *
     * @param mtime the value for archive_video_track.mtime, 修改时间
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * 获取 其他信息 字段:archive_video_track.remark
     *
     * @return archive_video_track.remark, 其他信息
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置 其他信息 字段:archive_video_track.remark
     *
     * @param remark the value for archive_video_track.remark, 其他信息
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * ,archive_video_track
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ArchiveVideoTrackId=").append(ArchiveVideoTrackId);
        sb.append(", aid=").append(aid);
        sb.append(", filename=").append(filename);
        sb.append(", status=").append(status);
        sb.append(", xcodeState=").append(xcodeState);
        sb.append(", ctime=").append(ctime);
        sb.append(", mtime=").append(mtime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}