package com.yanjinbin.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArchiveVideoEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_video
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_video
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_video
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    protected Integer limit;

    protected Integer offset;

    /**
     *  构造查询条件,archive_video
     */
    public ArchiveVideoEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,archive_video
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,archive_video
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,archive_video
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,archive_video
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,archive_video
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,archive_video
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,archive_video
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,archive_video
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,archive_video
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,archive_video
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        offset = null;
        limit = null;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return this.limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public ArchiveVideoEntityExample limit(Integer offset) {
        this.offset = offset;
        return this;
    }

    public ArchiveVideoEntityExample limit(Integer limit, Integer offset) {
        this.limit = limit;
        this.offset = offset;
        return this;
    }

    public ArchiveVideoEntityExample page(Integer page, Integer pageSize) {
        this.limit = page * pageSize;
        this.offset = pageSize;
        return this;
    }

    /**
     * archive_video
     * GeneratedCriteria
     * 数据库表：archive_video
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andArchiveVideoIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andArchiveVideoIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andArchiveVideoIdEqualTo(Integer value) {
            addCriterion("id =", value, "ArchiveVideoId");
            return (Criteria) this;
        }

        public Criteria andArchiveVideoIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "ArchiveVideoId");
            return (Criteria) this;
        }

        public Criteria andArchiveVideoIdGreaterThan(Integer value) {
            addCriterion("id >", value, "ArchiveVideoId");
            return (Criteria) this;
        }

        public Criteria andArchiveVideoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "ArchiveVideoId");
            return (Criteria) this;
        }

        public Criteria andArchiveVideoIdLessThan(Integer value) {
            addCriterion("id <", value, "ArchiveVideoId");
            return (Criteria) this;
        }

        public Criteria andArchiveVideoIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "ArchiveVideoId");
            return (Criteria) this;
        }

        public Criteria andArchiveVideoIdIn(List<Integer> values) {
            addCriterion("id in", values, "ArchiveVideoId");
            return (Criteria) this;
        }

        public Criteria andArchiveVideoIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "ArchiveVideoId");
            return (Criteria) this;
        }

        public Criteria andArchiveVideoIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "ArchiveVideoId");
            return (Criteria) this;
        }

        public Criteria andArchiveVideoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "ArchiveVideoId");
            return (Criteria) this;
        }

        public Criteria andAidIsNull() {
            addCriterion("aid is null");
            return (Criteria) this;
        }

        public Criteria andAidIsNotNull() {
            addCriterion("aid is not null");
            return (Criteria) this;
        }

        public Criteria andAidEqualTo(Integer value) {
            addCriterion("aid =", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotEqualTo(Integer value) {
            addCriterion("aid <>", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThan(Integer value) {
            addCriterion("aid >", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThanOrEqualTo(Integer value) {
            addCriterion("aid >=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThan(Integer value) {
            addCriterion("aid <", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThanOrEqualTo(Integer value) {
            addCriterion("aid <=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidIn(List<Integer> values) {
            addCriterion("aid in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotIn(List<Integer> values) {
            addCriterion("aid not in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidBetween(Integer value1, Integer value2) {
            addCriterion("aid between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotBetween(Integer value1, Integer value2) {
            addCriterion("aid not between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andEptitleIsNull() {
            addCriterion("eptitle is null");
            return (Criteria) this;
        }

        public Criteria andEptitleIsNotNull() {
            addCriterion("eptitle is not null");
            return (Criteria) this;
        }

        public Criteria andEptitleEqualTo(String value) {
            addCriterion("eptitle =", value, "eptitle");
            return (Criteria) this;
        }

        public Criteria andEptitleNotEqualTo(String value) {
            addCriterion("eptitle <>", value, "eptitle");
            return (Criteria) this;
        }

        public Criteria andEptitleGreaterThan(String value) {
            addCriterion("eptitle >", value, "eptitle");
            return (Criteria) this;
        }

        public Criteria andEptitleGreaterThanOrEqualTo(String value) {
            addCriterion("eptitle >=", value, "eptitle");
            return (Criteria) this;
        }

        public Criteria andEptitleLessThan(String value) {
            addCriterion("eptitle <", value, "eptitle");
            return (Criteria) this;
        }

        public Criteria andEptitleLessThanOrEqualTo(String value) {
            addCriterion("eptitle <=", value, "eptitle");
            return (Criteria) this;
        }

        public Criteria andEptitleLike(String value) {
            addCriterion("eptitle like", value, "eptitle");
            return (Criteria) this;
        }

        public Criteria andEptitleNotLike(String value) {
            addCriterion("eptitle not like", value, "eptitle");
            return (Criteria) this;
        }

        public Criteria andEptitleIn(List<String> values) {
            addCriterion("eptitle in", values, "eptitle");
            return (Criteria) this;
        }

        public Criteria andEptitleNotIn(List<String> values) {
            addCriterion("eptitle not in", values, "eptitle");
            return (Criteria) this;
        }

        public Criteria andEptitleBetween(String value1, String value2) {
            addCriterion("eptitle between", value1, value2, "eptitle");
            return (Criteria) this;
        }

        public Criteria andEptitleNotBetween(String value1, String value2) {
            addCriterion("eptitle not between", value1, value2, "eptitle");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNull() {
            addCriterion("filename is null");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNotNull() {
            addCriterion("filename is not null");
            return (Criteria) this;
        }

        public Criteria andFilenameEqualTo(String value) {
            addCriterion("filename =", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotEqualTo(String value) {
            addCriterion("filename <>", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThan(String value) {
            addCriterion("filename >", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThanOrEqualTo(String value) {
            addCriterion("filename >=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThan(String value) {
            addCriterion("filename <", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThanOrEqualTo(String value) {
            addCriterion("filename <=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLike(String value) {
            addCriterion("filename like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotLike(String value) {
            addCriterion("filename not like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameIn(List<String> values) {
            addCriterion("filename in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotIn(List<String> values) {
            addCriterion("filename not in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameBetween(String value1, String value2) {
            addCriterion("filename between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotBetween(String value1, String value2) {
            addCriterion("filename not between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andSrcTypeIsNull() {
            addCriterion("src_type is null");
            return (Criteria) this;
        }

        public Criteria andSrcTypeIsNotNull() {
            addCriterion("src_type is not null");
            return (Criteria) this;
        }

        public Criteria andSrcTypeEqualTo(String value) {
            addCriterion("src_type =", value, "srcType");
            return (Criteria) this;
        }

        public Criteria andSrcTypeNotEqualTo(String value) {
            addCriterion("src_type <>", value, "srcType");
            return (Criteria) this;
        }

        public Criteria andSrcTypeGreaterThan(String value) {
            addCriterion("src_type >", value, "srcType");
            return (Criteria) this;
        }

        public Criteria andSrcTypeGreaterThanOrEqualTo(String value) {
            addCriterion("src_type >=", value, "srcType");
            return (Criteria) this;
        }

        public Criteria andSrcTypeLessThan(String value) {
            addCriterion("src_type <", value, "srcType");
            return (Criteria) this;
        }

        public Criteria andSrcTypeLessThanOrEqualTo(String value) {
            addCriterion("src_type <=", value, "srcType");
            return (Criteria) this;
        }

        public Criteria andSrcTypeLike(String value) {
            addCriterion("src_type like", value, "srcType");
            return (Criteria) this;
        }

        public Criteria andSrcTypeNotLike(String value) {
            addCriterion("src_type not like", value, "srcType");
            return (Criteria) this;
        }

        public Criteria andSrcTypeIn(List<String> values) {
            addCriterion("src_type in", values, "srcType");
            return (Criteria) this;
        }

        public Criteria andSrcTypeNotIn(List<String> values) {
            addCriterion("src_type not in", values, "srcType");
            return (Criteria) this;
        }

        public Criteria andSrcTypeBetween(String value1, String value2) {
            addCriterion("src_type between", value1, value2, "srcType");
            return (Criteria) this;
        }

        public Criteria andSrcTypeNotBetween(String value1, String value2) {
            addCriterion("src_type not between", value1, value2, "srcType");
            return (Criteria) this;
        }

        public Criteria andCidIsNull() {
            addCriterion("cid is null");
            return (Criteria) this;
        }

        public Criteria andCidIsNotNull() {
            addCriterion("cid is not null");
            return (Criteria) this;
        }

        public Criteria andCidEqualTo(Integer value) {
            addCriterion("cid =", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotEqualTo(Integer value) {
            addCriterion("cid <>", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThan(Integer value) {
            addCriterion("cid >", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cid >=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThan(Integer value) {
            addCriterion("cid <", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThanOrEqualTo(Integer value) {
            addCriterion("cid <=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidIn(List<Integer> values) {
            addCriterion("cid in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotIn(List<Integer> values) {
            addCriterion("cid not in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidBetween(Integer value1, Integer value2) {
            addCriterion("cid between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotBetween(Integer value1, Integer value2) {
            addCriterion("cid not between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("duration is null");
            return (Criteria) this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("duration is not null");
            return (Criteria) this;
        }

        public Criteria andDurationEqualTo(Integer value) {
            addCriterion("duration =", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotEqualTo(Integer value) {
            addCriterion("duration <>", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThan(Integer value) {
            addCriterion("duration >", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("duration >=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThan(Integer value) {
            addCriterion("duration <", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThanOrEqualTo(Integer value) {
            addCriterion("duration <=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationIn(List<Integer> values) {
            addCriterion("duration in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotIn(List<Integer> values) {
            addCriterion("duration not in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationBetween(Integer value1, Integer value2) {
            addCriterion("duration between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("duration not between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andFilesizeIsNull() {
            addCriterion("filesize is null");
            return (Criteria) this;
        }

        public Criteria andFilesizeIsNotNull() {
            addCriterion("filesize is not null");
            return (Criteria) this;
        }

        public Criteria andFilesizeEqualTo(Integer value) {
            addCriterion("filesize =", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeNotEqualTo(Integer value) {
            addCriterion("filesize <>", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeGreaterThan(Integer value) {
            addCriterion("filesize >", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("filesize >=", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeLessThan(Integer value) {
            addCriterion("filesize <", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeLessThanOrEqualTo(Integer value) {
            addCriterion("filesize <=", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeIn(List<Integer> values) {
            addCriterion("filesize in", values, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeNotIn(List<Integer> values) {
            addCriterion("filesize not in", values, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeBetween(Integer value1, Integer value2) {
            addCriterion("filesize between", value1, value2, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeNotBetween(Integer value1, Integer value2) {
            addCriterion("filesize not between", value1, value2, "filesize");
            return (Criteria) this;
        }

        public Criteria andResolutionsIsNull() {
            addCriterion("resolutions is null");
            return (Criteria) this;
        }

        public Criteria andResolutionsIsNotNull() {
            addCriterion("resolutions is not null");
            return (Criteria) this;
        }

        public Criteria andResolutionsEqualTo(String value) {
            addCriterion("resolutions =", value, "resolutions");
            return (Criteria) this;
        }

        public Criteria andResolutionsNotEqualTo(String value) {
            addCriterion("resolutions <>", value, "resolutions");
            return (Criteria) this;
        }

        public Criteria andResolutionsGreaterThan(String value) {
            addCriterion("resolutions >", value, "resolutions");
            return (Criteria) this;
        }

        public Criteria andResolutionsGreaterThanOrEqualTo(String value) {
            addCriterion("resolutions >=", value, "resolutions");
            return (Criteria) this;
        }

        public Criteria andResolutionsLessThan(String value) {
            addCriterion("resolutions <", value, "resolutions");
            return (Criteria) this;
        }

        public Criteria andResolutionsLessThanOrEqualTo(String value) {
            addCriterion("resolutions <=", value, "resolutions");
            return (Criteria) this;
        }

        public Criteria andResolutionsLike(String value) {
            addCriterion("resolutions like", value, "resolutions");
            return (Criteria) this;
        }

        public Criteria andResolutionsNotLike(String value) {
            addCriterion("resolutions not like", value, "resolutions");
            return (Criteria) this;
        }

        public Criteria andResolutionsIn(List<String> values) {
            addCriterion("resolutions in", values, "resolutions");
            return (Criteria) this;
        }

        public Criteria andResolutionsNotIn(List<String> values) {
            addCriterion("resolutions not in", values, "resolutions");
            return (Criteria) this;
        }

        public Criteria andResolutionsBetween(String value1, String value2) {
            addCriterion("resolutions between", value1, value2, "resolutions");
            return (Criteria) this;
        }

        public Criteria andResolutionsNotBetween(String value1, String value2) {
            addCriterion("resolutions not between", value1, value2, "resolutions");
            return (Criteria) this;
        }

        public Criteria andIndexOrderIsNull() {
            addCriterion("index_order is null");
            return (Criteria) this;
        }

        public Criteria andIndexOrderIsNotNull() {
            addCriterion("index_order is not null");
            return (Criteria) this;
        }

        public Criteria andIndexOrderEqualTo(Integer value) {
            addCriterion("index_order =", value, "indexOrder");
            return (Criteria) this;
        }

        public Criteria andIndexOrderNotEqualTo(Integer value) {
            addCriterion("index_order <>", value, "indexOrder");
            return (Criteria) this;
        }

        public Criteria andIndexOrderGreaterThan(Integer value) {
            addCriterion("index_order >", value, "indexOrder");
            return (Criteria) this;
        }

        public Criteria andIndexOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("index_order >=", value, "indexOrder");
            return (Criteria) this;
        }

        public Criteria andIndexOrderLessThan(Integer value) {
            addCriterion("index_order <", value, "indexOrder");
            return (Criteria) this;
        }

        public Criteria andIndexOrderLessThanOrEqualTo(Integer value) {
            addCriterion("index_order <=", value, "indexOrder");
            return (Criteria) this;
        }

        public Criteria andIndexOrderIn(List<Integer> values) {
            addCriterion("index_order in", values, "indexOrder");
            return (Criteria) this;
        }

        public Criteria andIndexOrderNotIn(List<Integer> values) {
            addCriterion("index_order not in", values, "indexOrder");
            return (Criteria) this;
        }

        public Criteria andIndexOrderBetween(Integer value1, Integer value2) {
            addCriterion("index_order between", value1, value2, "indexOrder");
            return (Criteria) this;
        }

        public Criteria andIndexOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("index_order not between", value1, value2, "indexOrder");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(Date value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(Date value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(Date value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(Date value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(Date value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<Date> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<Date> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(Date value1, Date value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(Date value1, Date value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPlayurlIsNull() {
            addCriterion("playurl is null");
            return (Criteria) this;
        }

        public Criteria andPlayurlIsNotNull() {
            addCriterion("playurl is not null");
            return (Criteria) this;
        }

        public Criteria andPlayurlEqualTo(String value) {
            addCriterion("playurl =", value, "playurl");
            return (Criteria) this;
        }

        public Criteria andPlayurlNotEqualTo(String value) {
            addCriterion("playurl <>", value, "playurl");
            return (Criteria) this;
        }

        public Criteria andPlayurlGreaterThan(String value) {
            addCriterion("playurl >", value, "playurl");
            return (Criteria) this;
        }

        public Criteria andPlayurlGreaterThanOrEqualTo(String value) {
            addCriterion("playurl >=", value, "playurl");
            return (Criteria) this;
        }

        public Criteria andPlayurlLessThan(String value) {
            addCriterion("playurl <", value, "playurl");
            return (Criteria) this;
        }

        public Criteria andPlayurlLessThanOrEqualTo(String value) {
            addCriterion("playurl <=", value, "playurl");
            return (Criteria) this;
        }

        public Criteria andPlayurlLike(String value) {
            addCriterion("playurl like", value, "playurl");
            return (Criteria) this;
        }

        public Criteria andPlayurlNotLike(String value) {
            addCriterion("playurl not like", value, "playurl");
            return (Criteria) this;
        }

        public Criteria andPlayurlIn(List<String> values) {
            addCriterion("playurl in", values, "playurl");
            return (Criteria) this;
        }

        public Criteria andPlayurlNotIn(List<String> values) {
            addCriterion("playurl not in", values, "playurl");
            return (Criteria) this;
        }

        public Criteria andPlayurlBetween(String value1, String value2) {
            addCriterion("playurl between", value1, value2, "playurl");
            return (Criteria) this;
        }

        public Criteria andPlayurlNotBetween(String value1, String value2) {
            addCriterion("playurl not between", value1, value2, "playurl");
            return (Criteria) this;
        }

        public Criteria andAttributeIsNull() {
            addCriterion("`attribute` is null");
            return (Criteria) this;
        }

        public Criteria andAttributeIsNotNull() {
            addCriterion("`attribute` is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeEqualTo(Integer value) {
            addCriterion("`attribute` =", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeNotEqualTo(Integer value) {
            addCriterion("`attribute` <>", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeGreaterThan(Integer value) {
            addCriterion("`attribute` >", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`attribute` >=", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeLessThan(Integer value) {
            addCriterion("`attribute` <", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeLessThanOrEqualTo(Integer value) {
            addCriterion("`attribute` <=", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeIn(List<Integer> values) {
            addCriterion("`attribute` in", values, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeNotIn(List<Integer> values) {
            addCriterion("`attribute` not in", values, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeBetween(Integer value1, Integer value2) {
            addCriterion("`attribute` between", value1, value2, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeNotBetween(Integer value1, Integer value2) {
            addCriterion("`attribute` not between", value1, value2, "attribute");
            return (Criteria) this;
        }

        public Criteria andFailinfoIsNull() {
            addCriterion("failinfo is null");
            return (Criteria) this;
        }

        public Criteria andFailinfoIsNotNull() {
            addCriterion("failinfo is not null");
            return (Criteria) this;
        }

        public Criteria andFailinfoEqualTo(Byte value) {
            addCriterion("failinfo =", value, "failinfo");
            return (Criteria) this;
        }

        public Criteria andFailinfoNotEqualTo(Byte value) {
            addCriterion("failinfo <>", value, "failinfo");
            return (Criteria) this;
        }

        public Criteria andFailinfoGreaterThan(Byte value) {
            addCriterion("failinfo >", value, "failinfo");
            return (Criteria) this;
        }

        public Criteria andFailinfoGreaterThanOrEqualTo(Byte value) {
            addCriterion("failinfo >=", value, "failinfo");
            return (Criteria) this;
        }

        public Criteria andFailinfoLessThan(Byte value) {
            addCriterion("failinfo <", value, "failinfo");
            return (Criteria) this;
        }

        public Criteria andFailinfoLessThanOrEqualTo(Byte value) {
            addCriterion("failinfo <=", value, "failinfo");
            return (Criteria) this;
        }

        public Criteria andFailinfoIn(List<Byte> values) {
            addCriterion("failinfo in", values, "failinfo");
            return (Criteria) this;
        }

        public Criteria andFailinfoNotIn(List<Byte> values) {
            addCriterion("failinfo not in", values, "failinfo");
            return (Criteria) this;
        }

        public Criteria andFailinfoBetween(Byte value1, Byte value2) {
            addCriterion("failinfo between", value1, value2, "failinfo");
            return (Criteria) this;
        }

        public Criteria andFailinfoNotBetween(Byte value1, Byte value2) {
            addCriterion("failinfo not between", value1, value2, "failinfo");
            return (Criteria) this;
        }

        public Criteria andXcodeStateIsNull() {
            addCriterion("xcode_state is null");
            return (Criteria) this;
        }

        public Criteria andXcodeStateIsNotNull() {
            addCriterion("xcode_state is not null");
            return (Criteria) this;
        }

        public Criteria andXcodeStateEqualTo(Byte value) {
            addCriterion("xcode_state =", value, "xcodeState");
            return (Criteria) this;
        }

        public Criteria andXcodeStateNotEqualTo(Byte value) {
            addCriterion("xcode_state <>", value, "xcodeState");
            return (Criteria) this;
        }

        public Criteria andXcodeStateGreaterThan(Byte value) {
            addCriterion("xcode_state >", value, "xcodeState");
            return (Criteria) this;
        }

        public Criteria andXcodeStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("xcode_state >=", value, "xcodeState");
            return (Criteria) this;
        }

        public Criteria andXcodeStateLessThan(Byte value) {
            addCriterion("xcode_state <", value, "xcodeState");
            return (Criteria) this;
        }

        public Criteria andXcodeStateLessThanOrEqualTo(Byte value) {
            addCriterion("xcode_state <=", value, "xcodeState");
            return (Criteria) this;
        }

        public Criteria andXcodeStateIn(List<Byte> values) {
            addCriterion("xcode_state in", values, "xcodeState");
            return (Criteria) this;
        }

        public Criteria andXcodeStateNotIn(List<Byte> values) {
            addCriterion("xcode_state not in", values, "xcodeState");
            return (Criteria) this;
        }

        public Criteria andXcodeStateBetween(Byte value1, Byte value2) {
            addCriterion("xcode_state between", value1, value2, "xcodeState");
            return (Criteria) this;
        }

        public Criteria andXcodeStateNotBetween(Byte value1, Byte value2) {
            addCriterion("xcode_state not between", value1, value2, "xcodeState");
            return (Criteria) this;
        }

        public Criteria andWeblinkIsNull() {
            addCriterion("weblink is null");
            return (Criteria) this;
        }

        public Criteria andWeblinkIsNotNull() {
            addCriterion("weblink is not null");
            return (Criteria) this;
        }

        public Criteria andWeblinkEqualTo(String value) {
            addCriterion("weblink =", value, "weblink");
            return (Criteria) this;
        }

        public Criteria andWeblinkNotEqualTo(String value) {
            addCriterion("weblink <>", value, "weblink");
            return (Criteria) this;
        }

        public Criteria andWeblinkGreaterThan(String value) {
            addCriterion("weblink >", value, "weblink");
            return (Criteria) this;
        }

        public Criteria andWeblinkGreaterThanOrEqualTo(String value) {
            addCriterion("weblink >=", value, "weblink");
            return (Criteria) this;
        }

        public Criteria andWeblinkLessThan(String value) {
            addCriterion("weblink <", value, "weblink");
            return (Criteria) this;
        }

        public Criteria andWeblinkLessThanOrEqualTo(String value) {
            addCriterion("weblink <=", value, "weblink");
            return (Criteria) this;
        }

        public Criteria andWeblinkLike(String value) {
            addCriterion("weblink like", value, "weblink");
            return (Criteria) this;
        }

        public Criteria andWeblinkNotLike(String value) {
            addCriterion("weblink not like", value, "weblink");
            return (Criteria) this;
        }

        public Criteria andWeblinkIn(List<String> values) {
            addCriterion("weblink in", values, "weblink");
            return (Criteria) this;
        }

        public Criteria andWeblinkNotIn(List<String> values) {
            addCriterion("weblink not in", values, "weblink");
            return (Criteria) this;
        }

        public Criteria andWeblinkBetween(String value1, String value2) {
            addCriterion("weblink between", value1, value2, "weblink");
            return (Criteria) this;
        }

        public Criteria andWeblinkNotBetween(String value1, String value2) {
            addCriterion("weblink not between", value1, value2, "weblink");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：archive_video
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * archive_video
     * Criterion
     * 数据库表：archive_video
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}