package com.yanjinbin.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArchiveStageConfEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_stage_conf
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_stage_conf
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_stage_conf
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    protected Integer limit;

    protected Integer offset;

    /**
     *  构造查询条件,archive_stage_conf
     */
    public ArchiveStageConfEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,archive_stage_conf
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,archive_stage_conf
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,archive_stage_conf
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,archive_stage_conf
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,archive_stage_conf
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,archive_stage_conf
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,archive_stage_conf
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,archive_stage_conf
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,archive_stage_conf
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,archive_stage_conf
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        offset = null;
        limit = null;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return this.limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public ArchiveStageConfEntityExample limit(Integer offset) {
        this.offset = offset;
        return this;
    }

    public ArchiveStageConfEntityExample limit(Integer limit, Integer offset) {
        this.limit = limit;
        this.offset = offset;
        return this;
    }

    public ArchiveStageConfEntityExample page(Integer page, Integer pageSize) {
        this.limit = page * pageSize;
        this.offset = pageSize;
        return this;
    }

    /**
     * archive_stage_conf
     * GeneratedCriteria
     * 数据库表：archive_stage_conf
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andArchiveStageConfIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andArchiveStageConfIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andArchiveStageConfIdEqualTo(Long value) {
            addCriterion("id =", value, "ArchiveStageConfId");
            return (Criteria) this;
        }

        public Criteria andArchiveStageConfIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "ArchiveStageConfId");
            return (Criteria) this;
        }

        public Criteria andArchiveStageConfIdGreaterThan(Long value) {
            addCriterion("id >", value, "ArchiveStageConfId");
            return (Criteria) this;
        }

        public Criteria andArchiveStageConfIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "ArchiveStageConfId");
            return (Criteria) this;
        }

        public Criteria andArchiveStageConfIdLessThan(Long value) {
            addCriterion("id <", value, "ArchiveStageConfId");
            return (Criteria) this;
        }

        public Criteria andArchiveStageConfIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "ArchiveStageConfId");
            return (Criteria) this;
        }

        public Criteria andArchiveStageConfIdIn(List<Long> values) {
            addCriterion("id in", values, "ArchiveStageConfId");
            return (Criteria) this;
        }

        public Criteria andArchiveStageConfIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "ArchiveStageConfId");
            return (Criteria) this;
        }

        public Criteria andArchiveStageConfIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "ArchiveStageConfId");
            return (Criteria) this;
        }

        public Criteria andArchiveStageConfIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "ArchiveStageConfId");
            return (Criteria) this;
        }

        public Criteria andStageNameIsNull() {
            addCriterion("stage_name is null");
            return (Criteria) this;
        }

        public Criteria andStageNameIsNotNull() {
            addCriterion("stage_name is not null");
            return (Criteria) this;
        }

        public Criteria andStageNameEqualTo(String value) {
            addCriterion("stage_name =", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameNotEqualTo(String value) {
            addCriterion("stage_name <>", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameGreaterThan(String value) {
            addCriterion("stage_name >", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameGreaterThanOrEqualTo(String value) {
            addCriterion("stage_name >=", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameLessThan(String value) {
            addCriterion("stage_name <", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameLessThanOrEqualTo(String value) {
            addCriterion("stage_name <=", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameLike(String value) {
            addCriterion("stage_name like", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameNotLike(String value) {
            addCriterion("stage_name not like", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameIn(List<String> values) {
            addCriterion("stage_name in", values, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameNotIn(List<String> values) {
            addCriterion("stage_name not in", values, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameBetween(String value1, String value2) {
            addCriterion("stage_name between", value1, value2, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameNotBetween(String value1, String value2) {
            addCriterion("stage_name not between", value1, value2, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageValueIsNull() {
            addCriterion("stage_value is null");
            return (Criteria) this;
        }

        public Criteria andStageValueIsNotNull() {
            addCriterion("stage_value is not null");
            return (Criteria) this;
        }

        public Criteria andStageValueEqualTo(Byte value) {
            addCriterion("stage_value =", value, "stageValue");
            return (Criteria) this;
        }

        public Criteria andStageValueNotEqualTo(Byte value) {
            addCriterion("stage_value <>", value, "stageValue");
            return (Criteria) this;
        }

        public Criteria andStageValueGreaterThan(Byte value) {
            addCriterion("stage_value >", value, "stageValue");
            return (Criteria) this;
        }

        public Criteria andStageValueGreaterThanOrEqualTo(Byte value) {
            addCriterion("stage_value >=", value, "stageValue");
            return (Criteria) this;
        }

        public Criteria andStageValueLessThan(Byte value) {
            addCriterion("stage_value <", value, "stageValue");
            return (Criteria) this;
        }

        public Criteria andStageValueLessThanOrEqualTo(Byte value) {
            addCriterion("stage_value <=", value, "stageValue");
            return (Criteria) this;
        }

        public Criteria andStageValueIn(List<Byte> values) {
            addCriterion("stage_value in", values, "stageValue");
            return (Criteria) this;
        }

        public Criteria andStageValueNotIn(List<Byte> values) {
            addCriterion("stage_value not in", values, "stageValue");
            return (Criteria) this;
        }

        public Criteria andStageValueBetween(Byte value1, Byte value2) {
            addCriterion("stage_value between", value1, value2, "stageValue");
            return (Criteria) this;
        }

        public Criteria andStageValueNotBetween(Byte value1, Byte value2) {
            addCriterion("stage_value not between", value1, value2, "stageValue");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(Date value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(Date value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(Date value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(Date value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(Date value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<Date> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<Date> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(Date value1, Date value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(Date value1, Date value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：archive_stage_conf
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * archive_stage_conf
     * Criterion
     * 数据库表：archive_stage_conf
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}