package com.yanjinbin.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AvDailyChargeEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer rows;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    public AvDailyChargeEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public AvDailyChargeEntityExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public AvDailyChargeEntityExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public AvDailyChargeEntityExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andAvDailyChargeIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andAvDailyChargeIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andAvDailyChargeIdEqualTo(Integer value) {
            addCriterion("id =", value, "avDailyChargeId");
            return (Criteria) this;
        }

        public Criteria andAvDailyChargeIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "avDailyChargeId");
            return (Criteria) this;
        }

        public Criteria andAvDailyChargeIdGreaterThan(Integer value) {
            addCriterion("id >", value, "avDailyChargeId");
            return (Criteria) this;
        }

        public Criteria andAvDailyChargeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "avDailyChargeId");
            return (Criteria) this;
        }

        public Criteria andAvDailyChargeIdLessThan(Integer value) {
            addCriterion("id <", value, "avDailyChargeId");
            return (Criteria) this;
        }

        public Criteria andAvDailyChargeIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "avDailyChargeId");
            return (Criteria) this;
        }

        public Criteria andAvDailyChargeIdIn(List<Integer> values) {
            addCriterion("id in", values, "avDailyChargeId");
            return (Criteria) this;
        }

        public Criteria andAvDailyChargeIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "avDailyChargeId");
            return (Criteria) this;
        }

        public Criteria andAvDailyChargeIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "avDailyChargeId");
            return (Criteria) this;
        }

        public Criteria andAvDailyChargeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "avDailyChargeId");
            return (Criteria) this;
        }

        public Criteria andAvIdIsNull() {
            addCriterion("av_id is null");
            return (Criteria) this;
        }

        public Criteria andAvIdIsNotNull() {
            addCriterion("av_id is not null");
            return (Criteria) this;
        }

        public Criteria andAvIdEqualTo(Long value) {
            addCriterion("av_id =", value, "avId");
            return (Criteria) this;
        }

        public Criteria andAvIdNotEqualTo(Long value) {
            addCriterion("av_id <>", value, "avId");
            return (Criteria) this;
        }

        public Criteria andAvIdGreaterThan(Long value) {
            addCriterion("av_id >", value, "avId");
            return (Criteria) this;
        }

        public Criteria andAvIdGreaterThanOrEqualTo(Long value) {
            addCriterion("av_id >=", value, "avId");
            return (Criteria) this;
        }

        public Criteria andAvIdLessThan(Long value) {
            addCriterion("av_id <", value, "avId");
            return (Criteria) this;
        }

        public Criteria andAvIdLessThanOrEqualTo(Long value) {
            addCriterion("av_id <=", value, "avId");
            return (Criteria) this;
        }

        public Criteria andAvIdIn(List<Long> values) {
            addCriterion("av_id in", values, "avId");
            return (Criteria) this;
        }

        public Criteria andAvIdNotIn(List<Long> values) {
            addCriterion("av_id not in", values, "avId");
            return (Criteria) this;
        }

        public Criteria andAvIdBetween(Long value1, Long value2) {
            addCriterion("av_id between", value1, value2, "avId");
            return (Criteria) this;
        }

        public Criteria andAvIdNotBetween(Long value1, Long value2) {
            addCriterion("av_id not between", value1, value2, "avId");
            return (Criteria) this;
        }

        public Criteria andMidIsNull() {
            addCriterion("mid is null");
            return (Criteria) this;
        }

        public Criteria andMidIsNotNull() {
            addCriterion("mid is not null");
            return (Criteria) this;
        }

        public Criteria andMidEqualTo(Integer value) {
            addCriterion("mid =", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotEqualTo(Integer value) {
            addCriterion("mid <>", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThan(Integer value) {
            addCriterion("mid >", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThanOrEqualTo(Integer value) {
            addCriterion("mid >=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThan(Integer value) {
            addCriterion("mid <", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThanOrEqualTo(Integer value) {
            addCriterion("mid <=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidIn(List<Integer> values) {
            addCriterion("mid in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotIn(List<Integer> values) {
            addCriterion("mid not in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidBetween(Integer value1, Integer value2) {
            addCriterion("mid between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotBetween(Integer value1, Integer value2) {
            addCriterion("mid not between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andTagIdIsNull() {
            addCriterion("tag_id is null");
            return (Criteria) this;
        }

        public Criteria andTagIdIsNotNull() {
            addCriterion("tag_id is not null");
            return (Criteria) this;
        }

        public Criteria andTagIdEqualTo(Integer value) {
            addCriterion("tag_id =", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdNotEqualTo(Integer value) {
            addCriterion("tag_id <>", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdGreaterThan(Integer value) {
            addCriterion("tag_id >", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tag_id >=", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdLessThan(Integer value) {
            addCriterion("tag_id <", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdLessThanOrEqualTo(Integer value) {
            addCriterion("tag_id <=", value, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdIn(List<Integer> values) {
            addCriterion("tag_id in", values, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdNotIn(List<Integer> values) {
            addCriterion("tag_id not in", values, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdBetween(Integer value1, Integer value2) {
            addCriterion("tag_id between", value1, value2, "tagId");
            return (Criteria) this;
        }

        public Criteria andTagIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tag_id not between", value1, value2, "tagId");
            return (Criteria) this;
        }

        public Criteria andOriginalIsNull() {
            addCriterion("is_original is null");
            return (Criteria) this;
        }

        public Criteria andOriginalIsNotNull() {
            addCriterion("is_original is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalEqualTo(Integer value) {
            addCriterion("is_original =", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalNotEqualTo(Integer value) {
            addCriterion("is_original <>", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalGreaterThan(Integer value) {
            addCriterion("is_original >", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_original >=", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalLessThan(Integer value) {
            addCriterion("is_original <", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalLessThanOrEqualTo(Integer value) {
            addCriterion("is_original <=", value, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalIn(List<Integer> values) {
            addCriterion("is_original in", values, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalNotIn(List<Integer> values) {
            addCriterion("is_original not in", values, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalBetween(Integer value1, Integer value2) {
            addCriterion("is_original between", value1, value2, "original");
            return (Criteria) this;
        }

        public Criteria andOriginalNotBetween(Integer value1, Integer value2) {
            addCriterion("is_original not between", value1, value2, "original");
            return (Criteria) this;
        }

        public Criteria andUploadTimeIsNull() {
            addCriterion("upload_time is null");
            return (Criteria) this;
        }

        public Criteria andUploadTimeIsNotNull() {
            addCriterion("upload_time is not null");
            return (Criteria) this;
        }

        public Criteria andUploadTimeEqualTo(Date value) {
            addCriterion("upload_time =", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeNotEqualTo(Date value) {
            addCriterion("upload_time <>", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeGreaterThan(Date value) {
            addCriterion("upload_time >", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("upload_time >=", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeLessThan(Date value) {
            addCriterion("upload_time <", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeLessThanOrEqualTo(Date value) {
            addCriterion("upload_time <=", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeIn(List<Date> values) {
            addCriterion("upload_time in", values, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeNotIn(List<Date> values) {
            addCriterion("upload_time not in", values, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeBetween(Date value1, Date value2) {
            addCriterion("upload_time between", value1, value2, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeNotBetween(Date value1, Date value2) {
            addCriterion("upload_time not between", value1, value2, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andDanmakuCountIsNull() {
            addCriterion("danmaku_count is null");
            return (Criteria) this;
        }

        public Criteria andDanmakuCountIsNotNull() {
            addCriterion("danmaku_count is not null");
            return (Criteria) this;
        }

        public Criteria andDanmakuCountEqualTo(Integer value) {
            addCriterion("danmaku_count =", value, "danmakuCount");
            return (Criteria) this;
        }

        public Criteria andDanmakuCountNotEqualTo(Integer value) {
            addCriterion("danmaku_count <>", value, "danmakuCount");
            return (Criteria) this;
        }

        public Criteria andDanmakuCountGreaterThan(Integer value) {
            addCriterion("danmaku_count >", value, "danmakuCount");
            return (Criteria) this;
        }

        public Criteria andDanmakuCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("danmaku_count >=", value, "danmakuCount");
            return (Criteria) this;
        }

        public Criteria andDanmakuCountLessThan(Integer value) {
            addCriterion("danmaku_count <", value, "danmakuCount");
            return (Criteria) this;
        }

        public Criteria andDanmakuCountLessThanOrEqualTo(Integer value) {
            addCriterion("danmaku_count <=", value, "danmakuCount");
            return (Criteria) this;
        }

        public Criteria andDanmakuCountIn(List<Integer> values) {
            addCriterion("danmaku_count in", values, "danmakuCount");
            return (Criteria) this;
        }

        public Criteria andDanmakuCountNotIn(List<Integer> values) {
            addCriterion("danmaku_count not in", values, "danmakuCount");
            return (Criteria) this;
        }

        public Criteria andDanmakuCountBetween(Integer value1, Integer value2) {
            addCriterion("danmaku_count between", value1, value2, "danmakuCount");
            return (Criteria) this;
        }

        public Criteria andDanmakuCountNotBetween(Integer value1, Integer value2) {
            addCriterion("danmaku_count not between", value1, value2, "danmakuCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountIsNull() {
            addCriterion("comment_count is null");
            return (Criteria) this;
        }

        public Criteria andCommentCountIsNotNull() {
            addCriterion("comment_count is not null");
            return (Criteria) this;
        }

        public Criteria andCommentCountEqualTo(Integer value) {
            addCriterion("comment_count =", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotEqualTo(Integer value) {
            addCriterion("comment_count <>", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountGreaterThan(Integer value) {
            addCriterion("comment_count >", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_count >=", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountLessThan(Integer value) {
            addCriterion("comment_count <", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountLessThanOrEqualTo(Integer value) {
            addCriterion("comment_count <=", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountIn(List<Integer> values) {
            addCriterion("comment_count in", values, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotIn(List<Integer> values) {
            addCriterion("comment_count not in", values, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountBetween(Integer value1, Integer value2) {
            addCriterion("comment_count between", value1, value2, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_count not between", value1, value2, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCollectCountIsNull() {
            addCriterion("collect_count is null");
            return (Criteria) this;
        }

        public Criteria andCollectCountIsNotNull() {
            addCriterion("collect_count is not null");
            return (Criteria) this;
        }

        public Criteria andCollectCountEqualTo(Integer value) {
            addCriterion("collect_count =", value, "collectCount");
            return (Criteria) this;
        }

        public Criteria andCollectCountNotEqualTo(Integer value) {
            addCriterion("collect_count <>", value, "collectCount");
            return (Criteria) this;
        }

        public Criteria andCollectCountGreaterThan(Integer value) {
            addCriterion("collect_count >", value, "collectCount");
            return (Criteria) this;
        }

        public Criteria andCollectCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("collect_count >=", value, "collectCount");
            return (Criteria) this;
        }

        public Criteria andCollectCountLessThan(Integer value) {
            addCriterion("collect_count <", value, "collectCount");
            return (Criteria) this;
        }

        public Criteria andCollectCountLessThanOrEqualTo(Integer value) {
            addCriterion("collect_count <=", value, "collectCount");
            return (Criteria) this;
        }

        public Criteria andCollectCountIn(List<Integer> values) {
            addCriterion("collect_count in", values, "collectCount");
            return (Criteria) this;
        }

        public Criteria andCollectCountNotIn(List<Integer> values) {
            addCriterion("collect_count not in", values, "collectCount");
            return (Criteria) this;
        }

        public Criteria andCollectCountBetween(Integer value1, Integer value2) {
            addCriterion("collect_count between", value1, value2, "collectCount");
            return (Criteria) this;
        }

        public Criteria andCollectCountNotBetween(Integer value1, Integer value2) {
            addCriterion("collect_count not between", value1, value2, "collectCount");
            return (Criteria) this;
        }

        public Criteria andCoinCountIsNull() {
            addCriterion("coin_count is null");
            return (Criteria) this;
        }

        public Criteria andCoinCountIsNotNull() {
            addCriterion("coin_count is not null");
            return (Criteria) this;
        }

        public Criteria andCoinCountEqualTo(Integer value) {
            addCriterion("coin_count =", value, "coinCount");
            return (Criteria) this;
        }

        public Criteria andCoinCountNotEqualTo(Integer value) {
            addCriterion("coin_count <>", value, "coinCount");
            return (Criteria) this;
        }

        public Criteria andCoinCountGreaterThan(Integer value) {
            addCriterion("coin_count >", value, "coinCount");
            return (Criteria) this;
        }

        public Criteria andCoinCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("coin_count >=", value, "coinCount");
            return (Criteria) this;
        }

        public Criteria andCoinCountLessThan(Integer value) {
            addCriterion("coin_count <", value, "coinCount");
            return (Criteria) this;
        }

        public Criteria andCoinCountLessThanOrEqualTo(Integer value) {
            addCriterion("coin_count <=", value, "coinCount");
            return (Criteria) this;
        }

        public Criteria andCoinCountIn(List<Integer> values) {
            addCriterion("coin_count in", values, "coinCount");
            return (Criteria) this;
        }

        public Criteria andCoinCountNotIn(List<Integer> values) {
            addCriterion("coin_count not in", values, "coinCount");
            return (Criteria) this;
        }

        public Criteria andCoinCountBetween(Integer value1, Integer value2) {
            addCriterion("coin_count between", value1, value2, "coinCount");
            return (Criteria) this;
        }

        public Criteria andCoinCountNotBetween(Integer value1, Integer value2) {
            addCriterion("coin_count not between", value1, value2, "coinCount");
            return (Criteria) this;
        }

        public Criteria andShareCountIsNull() {
            addCriterion("share_count is null");
            return (Criteria) this;
        }

        public Criteria andShareCountIsNotNull() {
            addCriterion("share_count is not null");
            return (Criteria) this;
        }

        public Criteria andShareCountEqualTo(Integer value) {
            addCriterion("share_count =", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountNotEqualTo(Integer value) {
            addCriterion("share_count <>", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountGreaterThan(Integer value) {
            addCriterion("share_count >", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("share_count >=", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountLessThan(Integer value) {
            addCriterion("share_count <", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountLessThanOrEqualTo(Integer value) {
            addCriterion("share_count <=", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountIn(List<Integer> values) {
            addCriterion("share_count in", values, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountNotIn(List<Integer> values) {
            addCriterion("share_count not in", values, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountBetween(Integer value1, Integer value2) {
            addCriterion("share_count between", value1, value2, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountNotBetween(Integer value1, Integer value2) {
            addCriterion("share_count not between", value1, value2, "shareCount");
            return (Criteria) this;
        }

        public Criteria andElecPayCountIsNull() {
            addCriterion("elec_pay_count is null");
            return (Criteria) this;
        }

        public Criteria andElecPayCountIsNotNull() {
            addCriterion("elec_pay_count is not null");
            return (Criteria) this;
        }

        public Criteria andElecPayCountEqualTo(Integer value) {
            addCriterion("elec_pay_count =", value, "elecPayCount");
            return (Criteria) this;
        }

        public Criteria andElecPayCountNotEqualTo(Integer value) {
            addCriterion("elec_pay_count <>", value, "elecPayCount");
            return (Criteria) this;
        }

        public Criteria andElecPayCountGreaterThan(Integer value) {
            addCriterion("elec_pay_count >", value, "elecPayCount");
            return (Criteria) this;
        }

        public Criteria andElecPayCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("elec_pay_count >=", value, "elecPayCount");
            return (Criteria) this;
        }

        public Criteria andElecPayCountLessThan(Integer value) {
            addCriterion("elec_pay_count <", value, "elecPayCount");
            return (Criteria) this;
        }

        public Criteria andElecPayCountLessThanOrEqualTo(Integer value) {
            addCriterion("elec_pay_count <=", value, "elecPayCount");
            return (Criteria) this;
        }

        public Criteria andElecPayCountIn(List<Integer> values) {
            addCriterion("elec_pay_count in", values, "elecPayCount");
            return (Criteria) this;
        }

        public Criteria andElecPayCountNotIn(List<Integer> values) {
            addCriterion("elec_pay_count not in", values, "elecPayCount");
            return (Criteria) this;
        }

        public Criteria andElecPayCountBetween(Integer value1, Integer value2) {
            addCriterion("elec_pay_count between", value1, value2, "elecPayCount");
            return (Criteria) this;
        }

        public Criteria andElecPayCountNotBetween(Integer value1, Integer value2) {
            addCriterion("elec_pay_count not between", value1, value2, "elecPayCount");
            return (Criteria) this;
        }

        public Criteria andTotalPlayCountIsNull() {
            addCriterion("total_play_count is null");
            return (Criteria) this;
        }

        public Criteria andTotalPlayCountIsNotNull() {
            addCriterion("total_play_count is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPlayCountEqualTo(Integer value) {
            addCriterion("total_play_count =", value, "totalPlayCount");
            return (Criteria) this;
        }

        public Criteria andTotalPlayCountNotEqualTo(Integer value) {
            addCriterion("total_play_count <>", value, "totalPlayCount");
            return (Criteria) this;
        }

        public Criteria andTotalPlayCountGreaterThan(Integer value) {
            addCriterion("total_play_count >", value, "totalPlayCount");
            return (Criteria) this;
        }

        public Criteria andTotalPlayCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_play_count >=", value, "totalPlayCount");
            return (Criteria) this;
        }

        public Criteria andTotalPlayCountLessThan(Integer value) {
            addCriterion("total_play_count <", value, "totalPlayCount");
            return (Criteria) this;
        }

        public Criteria andTotalPlayCountLessThanOrEqualTo(Integer value) {
            addCriterion("total_play_count <=", value, "totalPlayCount");
            return (Criteria) this;
        }

        public Criteria andTotalPlayCountIn(List<Integer> values) {
            addCriterion("total_play_count in", values, "totalPlayCount");
            return (Criteria) this;
        }

        public Criteria andTotalPlayCountNotIn(List<Integer> values) {
            addCriterion("total_play_count not in", values, "totalPlayCount");
            return (Criteria) this;
        }

        public Criteria andTotalPlayCountBetween(Integer value1, Integer value2) {
            addCriterion("total_play_count between", value1, value2, "totalPlayCount");
            return (Criteria) this;
        }

        public Criteria andTotalPlayCountNotBetween(Integer value1, Integer value2) {
            addCriterion("total_play_count not between", value1, value2, "totalPlayCount");
            return (Criteria) this;
        }

        public Criteria andWebPlayCountIsNull() {
            addCriterion("web_play_count is null");
            return (Criteria) this;
        }

        public Criteria andWebPlayCountIsNotNull() {
            addCriterion("web_play_count is not null");
            return (Criteria) this;
        }

        public Criteria andWebPlayCountEqualTo(Integer value) {
            addCriterion("web_play_count =", value, "webPlayCount");
            return (Criteria) this;
        }

        public Criteria andWebPlayCountNotEqualTo(Integer value) {
            addCriterion("web_play_count <>", value, "webPlayCount");
            return (Criteria) this;
        }

        public Criteria andWebPlayCountGreaterThan(Integer value) {
            addCriterion("web_play_count >", value, "webPlayCount");
            return (Criteria) this;
        }

        public Criteria andWebPlayCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("web_play_count >=", value, "webPlayCount");
            return (Criteria) this;
        }

        public Criteria andWebPlayCountLessThan(Integer value) {
            addCriterion("web_play_count <", value, "webPlayCount");
            return (Criteria) this;
        }

        public Criteria andWebPlayCountLessThanOrEqualTo(Integer value) {
            addCriterion("web_play_count <=", value, "webPlayCount");
            return (Criteria) this;
        }

        public Criteria andWebPlayCountIn(List<Integer> values) {
            addCriterion("web_play_count in", values, "webPlayCount");
            return (Criteria) this;
        }

        public Criteria andWebPlayCountNotIn(List<Integer> values) {
            addCriterion("web_play_count not in", values, "webPlayCount");
            return (Criteria) this;
        }

        public Criteria andWebPlayCountBetween(Integer value1, Integer value2) {
            addCriterion("web_play_count between", value1, value2, "webPlayCount");
            return (Criteria) this;
        }

        public Criteria andWebPlayCountNotBetween(Integer value1, Integer value2) {
            addCriterion("web_play_count not between", value1, value2, "webPlayCount");
            return (Criteria) this;
        }

        public Criteria andAppPlayCountIsNull() {
            addCriterion("app_play_count is null");
            return (Criteria) this;
        }

        public Criteria andAppPlayCountIsNotNull() {
            addCriterion("app_play_count is not null");
            return (Criteria) this;
        }

        public Criteria andAppPlayCountEqualTo(Integer value) {
            addCriterion("app_play_count =", value, "appPlayCount");
            return (Criteria) this;
        }

        public Criteria andAppPlayCountNotEqualTo(Integer value) {
            addCriterion("app_play_count <>", value, "appPlayCount");
            return (Criteria) this;
        }

        public Criteria andAppPlayCountGreaterThan(Integer value) {
            addCriterion("app_play_count >", value, "appPlayCount");
            return (Criteria) this;
        }

        public Criteria andAppPlayCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("app_play_count >=", value, "appPlayCount");
            return (Criteria) this;
        }

        public Criteria andAppPlayCountLessThan(Integer value) {
            addCriterion("app_play_count <", value, "appPlayCount");
            return (Criteria) this;
        }

        public Criteria andAppPlayCountLessThanOrEqualTo(Integer value) {
            addCriterion("app_play_count <=", value, "appPlayCount");
            return (Criteria) this;
        }

        public Criteria andAppPlayCountIn(List<Integer> values) {
            addCriterion("app_play_count in", values, "appPlayCount");
            return (Criteria) this;
        }

        public Criteria andAppPlayCountNotIn(List<Integer> values) {
            addCriterion("app_play_count not in", values, "appPlayCount");
            return (Criteria) this;
        }

        public Criteria andAppPlayCountBetween(Integer value1, Integer value2) {
            addCriterion("app_play_count between", value1, value2, "appPlayCount");
            return (Criteria) this;
        }

        public Criteria andAppPlayCountNotBetween(Integer value1, Integer value2) {
            addCriterion("app_play_count not between", value1, value2, "appPlayCount");
            return (Criteria) this;
        }

        public Criteria andH5PlayCountIsNull() {
            addCriterion("h5_play_count is null");
            return (Criteria) this;
        }

        public Criteria andH5PlayCountIsNotNull() {
            addCriterion("h5_play_count is not null");
            return (Criteria) this;
        }

        public Criteria andH5PlayCountEqualTo(Integer value) {
            addCriterion("h5_play_count =", value, "h5PlayCount");
            return (Criteria) this;
        }

        public Criteria andH5PlayCountNotEqualTo(Integer value) {
            addCriterion("h5_play_count <>", value, "h5PlayCount");
            return (Criteria) this;
        }

        public Criteria andH5PlayCountGreaterThan(Integer value) {
            addCriterion("h5_play_count >", value, "h5PlayCount");
            return (Criteria) this;
        }

        public Criteria andH5PlayCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("h5_play_count >=", value, "h5PlayCount");
            return (Criteria) this;
        }

        public Criteria andH5PlayCountLessThan(Integer value) {
            addCriterion("h5_play_count <", value, "h5PlayCount");
            return (Criteria) this;
        }

        public Criteria andH5PlayCountLessThanOrEqualTo(Integer value) {
            addCriterion("h5_play_count <=", value, "h5PlayCount");
            return (Criteria) this;
        }

        public Criteria andH5PlayCountIn(List<Integer> values) {
            addCriterion("h5_play_count in", values, "h5PlayCount");
            return (Criteria) this;
        }

        public Criteria andH5PlayCountNotIn(List<Integer> values) {
            addCriterion("h5_play_count not in", values, "h5PlayCount");
            return (Criteria) this;
        }

        public Criteria andH5PlayCountBetween(Integer value1, Integer value2) {
            addCriterion("h5_play_count between", value1, value2, "h5PlayCount");
            return (Criteria) this;
        }

        public Criteria andH5PlayCountNotBetween(Integer value1, Integer value2) {
            addCriterion("h5_play_count not between", value1, value2, "h5PlayCount");
            return (Criteria) this;
        }

        public Criteria andLvUnknownIsNull() {
            addCriterion("lv_unknown is null");
            return (Criteria) this;
        }

        public Criteria andLvUnknownIsNotNull() {
            addCriterion("lv_unknown is not null");
            return (Criteria) this;
        }

        public Criteria andLvUnknownEqualTo(Integer value) {
            addCriterion("lv_unknown =", value, "lvUnknown");
            return (Criteria) this;
        }

        public Criteria andLvUnknownNotEqualTo(Integer value) {
            addCriterion("lv_unknown <>", value, "lvUnknown");
            return (Criteria) this;
        }

        public Criteria andLvUnknownGreaterThan(Integer value) {
            addCriterion("lv_unknown >", value, "lvUnknown");
            return (Criteria) this;
        }

        public Criteria andLvUnknownGreaterThanOrEqualTo(Integer value) {
            addCriterion("lv_unknown >=", value, "lvUnknown");
            return (Criteria) this;
        }

        public Criteria andLvUnknownLessThan(Integer value) {
            addCriterion("lv_unknown <", value, "lvUnknown");
            return (Criteria) this;
        }

        public Criteria andLvUnknownLessThanOrEqualTo(Integer value) {
            addCriterion("lv_unknown <=", value, "lvUnknown");
            return (Criteria) this;
        }

        public Criteria andLvUnknownIn(List<Integer> values) {
            addCriterion("lv_unknown in", values, "lvUnknown");
            return (Criteria) this;
        }

        public Criteria andLvUnknownNotIn(List<Integer> values) {
            addCriterion("lv_unknown not in", values, "lvUnknown");
            return (Criteria) this;
        }

        public Criteria andLvUnknownBetween(Integer value1, Integer value2) {
            addCriterion("lv_unknown between", value1, value2, "lvUnknown");
            return (Criteria) this;
        }

        public Criteria andLvUnknownNotBetween(Integer value1, Integer value2) {
            addCriterion("lv_unknown not between", value1, value2, "lvUnknown");
            return (Criteria) this;
        }

        public Criteria andLv0IsNull() {
            addCriterion("lv_0 is null");
            return (Criteria) this;
        }

        public Criteria andLv0IsNotNull() {
            addCriterion("lv_0 is not null");
            return (Criteria) this;
        }

        public Criteria andLv0EqualTo(Integer value) {
            addCriterion("lv_0 =", value, "lv0");
            return (Criteria) this;
        }

        public Criteria andLv0NotEqualTo(Integer value) {
            addCriterion("lv_0 <>", value, "lv0");
            return (Criteria) this;
        }

        public Criteria andLv0GreaterThan(Integer value) {
            addCriterion("lv_0 >", value, "lv0");
            return (Criteria) this;
        }

        public Criteria andLv0GreaterThanOrEqualTo(Integer value) {
            addCriterion("lv_0 >=", value, "lv0");
            return (Criteria) this;
        }

        public Criteria andLv0LessThan(Integer value) {
            addCriterion("lv_0 <", value, "lv0");
            return (Criteria) this;
        }

        public Criteria andLv0LessThanOrEqualTo(Integer value) {
            addCriterion("lv_0 <=", value, "lv0");
            return (Criteria) this;
        }

        public Criteria andLv0In(List<Integer> values) {
            addCriterion("lv_0 in", values, "lv0");
            return (Criteria) this;
        }

        public Criteria andLv0NotIn(List<Integer> values) {
            addCriterion("lv_0 not in", values, "lv0");
            return (Criteria) this;
        }

        public Criteria andLv0Between(Integer value1, Integer value2) {
            addCriterion("lv_0 between", value1, value2, "lv0");
            return (Criteria) this;
        }

        public Criteria andLv0NotBetween(Integer value1, Integer value2) {
            addCriterion("lv_0 not between", value1, value2, "lv0");
            return (Criteria) this;
        }

        public Criteria andLv1IsNull() {
            addCriterion("lv_1 is null");
            return (Criteria) this;
        }

        public Criteria andLv1IsNotNull() {
            addCriterion("lv_1 is not null");
            return (Criteria) this;
        }

        public Criteria andLv1EqualTo(Integer value) {
            addCriterion("lv_1 =", value, "lv1");
            return (Criteria) this;
        }

        public Criteria andLv1NotEqualTo(Integer value) {
            addCriterion("lv_1 <>", value, "lv1");
            return (Criteria) this;
        }

        public Criteria andLv1GreaterThan(Integer value) {
            addCriterion("lv_1 >", value, "lv1");
            return (Criteria) this;
        }

        public Criteria andLv1GreaterThanOrEqualTo(Integer value) {
            addCriterion("lv_1 >=", value, "lv1");
            return (Criteria) this;
        }

        public Criteria andLv1LessThan(Integer value) {
            addCriterion("lv_1 <", value, "lv1");
            return (Criteria) this;
        }

        public Criteria andLv1LessThanOrEqualTo(Integer value) {
            addCriterion("lv_1 <=", value, "lv1");
            return (Criteria) this;
        }

        public Criteria andLv1In(List<Integer> values) {
            addCriterion("lv_1 in", values, "lv1");
            return (Criteria) this;
        }

        public Criteria andLv1NotIn(List<Integer> values) {
            addCriterion("lv_1 not in", values, "lv1");
            return (Criteria) this;
        }

        public Criteria andLv1Between(Integer value1, Integer value2) {
            addCriterion("lv_1 between", value1, value2, "lv1");
            return (Criteria) this;
        }

        public Criteria andLv1NotBetween(Integer value1, Integer value2) {
            addCriterion("lv_1 not between", value1, value2, "lv1");
            return (Criteria) this;
        }

        public Criteria andLv2IsNull() {
            addCriterion("lv_2 is null");
            return (Criteria) this;
        }

        public Criteria andLv2IsNotNull() {
            addCriterion("lv_2 is not null");
            return (Criteria) this;
        }

        public Criteria andLv2EqualTo(Integer value) {
            addCriterion("lv_2 =", value, "lv2");
            return (Criteria) this;
        }

        public Criteria andLv2NotEqualTo(Integer value) {
            addCriterion("lv_2 <>", value, "lv2");
            return (Criteria) this;
        }

        public Criteria andLv2GreaterThan(Integer value) {
            addCriterion("lv_2 >", value, "lv2");
            return (Criteria) this;
        }

        public Criteria andLv2GreaterThanOrEqualTo(Integer value) {
            addCriterion("lv_2 >=", value, "lv2");
            return (Criteria) this;
        }

        public Criteria andLv2LessThan(Integer value) {
            addCriterion("lv_2 <", value, "lv2");
            return (Criteria) this;
        }

        public Criteria andLv2LessThanOrEqualTo(Integer value) {
            addCriterion("lv_2 <=", value, "lv2");
            return (Criteria) this;
        }

        public Criteria andLv2In(List<Integer> values) {
            addCriterion("lv_2 in", values, "lv2");
            return (Criteria) this;
        }

        public Criteria andLv2NotIn(List<Integer> values) {
            addCriterion("lv_2 not in", values, "lv2");
            return (Criteria) this;
        }

        public Criteria andLv2Between(Integer value1, Integer value2) {
            addCriterion("lv_2 between", value1, value2, "lv2");
            return (Criteria) this;
        }

        public Criteria andLv2NotBetween(Integer value1, Integer value2) {
            addCriterion("lv_2 not between", value1, value2, "lv2");
            return (Criteria) this;
        }

        public Criteria andLv3IsNull() {
            addCriterion("lv_3 is null");
            return (Criteria) this;
        }

        public Criteria andLv3IsNotNull() {
            addCriterion("lv_3 is not null");
            return (Criteria) this;
        }

        public Criteria andLv3EqualTo(Integer value) {
            addCriterion("lv_3 =", value, "lv3");
            return (Criteria) this;
        }

        public Criteria andLv3NotEqualTo(Integer value) {
            addCriterion("lv_3 <>", value, "lv3");
            return (Criteria) this;
        }

        public Criteria andLv3GreaterThan(Integer value) {
            addCriterion("lv_3 >", value, "lv3");
            return (Criteria) this;
        }

        public Criteria andLv3GreaterThanOrEqualTo(Integer value) {
            addCriterion("lv_3 >=", value, "lv3");
            return (Criteria) this;
        }

        public Criteria andLv3LessThan(Integer value) {
            addCriterion("lv_3 <", value, "lv3");
            return (Criteria) this;
        }

        public Criteria andLv3LessThanOrEqualTo(Integer value) {
            addCriterion("lv_3 <=", value, "lv3");
            return (Criteria) this;
        }

        public Criteria andLv3In(List<Integer> values) {
            addCriterion("lv_3 in", values, "lv3");
            return (Criteria) this;
        }

        public Criteria andLv3NotIn(List<Integer> values) {
            addCriterion("lv_3 not in", values, "lv3");
            return (Criteria) this;
        }

        public Criteria andLv3Between(Integer value1, Integer value2) {
            addCriterion("lv_3 between", value1, value2, "lv3");
            return (Criteria) this;
        }

        public Criteria andLv3NotBetween(Integer value1, Integer value2) {
            addCriterion("lv_3 not between", value1, value2, "lv3");
            return (Criteria) this;
        }

        public Criteria andLv4IsNull() {
            addCriterion("lv_4 is null");
            return (Criteria) this;
        }

        public Criteria andLv4IsNotNull() {
            addCriterion("lv_4 is not null");
            return (Criteria) this;
        }

        public Criteria andLv4EqualTo(Integer value) {
            addCriterion("lv_4 =", value, "lv4");
            return (Criteria) this;
        }

        public Criteria andLv4NotEqualTo(Integer value) {
            addCriterion("lv_4 <>", value, "lv4");
            return (Criteria) this;
        }

        public Criteria andLv4GreaterThan(Integer value) {
            addCriterion("lv_4 >", value, "lv4");
            return (Criteria) this;
        }

        public Criteria andLv4GreaterThanOrEqualTo(Integer value) {
            addCriterion("lv_4 >=", value, "lv4");
            return (Criteria) this;
        }

        public Criteria andLv4LessThan(Integer value) {
            addCriterion("lv_4 <", value, "lv4");
            return (Criteria) this;
        }

        public Criteria andLv4LessThanOrEqualTo(Integer value) {
            addCriterion("lv_4 <=", value, "lv4");
            return (Criteria) this;
        }

        public Criteria andLv4In(List<Integer> values) {
            addCriterion("lv_4 in", values, "lv4");
            return (Criteria) this;
        }

        public Criteria andLv4NotIn(List<Integer> values) {
            addCriterion("lv_4 not in", values, "lv4");
            return (Criteria) this;
        }

        public Criteria andLv4Between(Integer value1, Integer value2) {
            addCriterion("lv_4 between", value1, value2, "lv4");
            return (Criteria) this;
        }

        public Criteria andLv4NotBetween(Integer value1, Integer value2) {
            addCriterion("lv_4 not between", value1, value2, "lv4");
            return (Criteria) this;
        }

        public Criteria andLv5IsNull() {
            addCriterion("lv_5 is null");
            return (Criteria) this;
        }

        public Criteria andLv5IsNotNull() {
            addCriterion("lv_5 is not null");
            return (Criteria) this;
        }

        public Criteria andLv5EqualTo(Integer value) {
            addCriterion("lv_5 =", value, "lv5");
            return (Criteria) this;
        }

        public Criteria andLv5NotEqualTo(Integer value) {
            addCriterion("lv_5 <>", value, "lv5");
            return (Criteria) this;
        }

        public Criteria andLv5GreaterThan(Integer value) {
            addCriterion("lv_5 >", value, "lv5");
            return (Criteria) this;
        }

        public Criteria andLv5GreaterThanOrEqualTo(Integer value) {
            addCriterion("lv_5 >=", value, "lv5");
            return (Criteria) this;
        }

        public Criteria andLv5LessThan(Integer value) {
            addCriterion("lv_5 <", value, "lv5");
            return (Criteria) this;
        }

        public Criteria andLv5LessThanOrEqualTo(Integer value) {
            addCriterion("lv_5 <=", value, "lv5");
            return (Criteria) this;
        }

        public Criteria andLv5In(List<Integer> values) {
            addCriterion("lv_5 in", values, "lv5");
            return (Criteria) this;
        }

        public Criteria andLv5NotIn(List<Integer> values) {
            addCriterion("lv_5 not in", values, "lv5");
            return (Criteria) this;
        }

        public Criteria andLv5Between(Integer value1, Integer value2) {
            addCriterion("lv_5 between", value1, value2, "lv5");
            return (Criteria) this;
        }

        public Criteria andLv5NotBetween(Integer value1, Integer value2) {
            addCriterion("lv_5 not between", value1, value2, "lv5");
            return (Criteria) this;
        }

        public Criteria andLv6IsNull() {
            addCriterion("lv_6 is null");
            return (Criteria) this;
        }

        public Criteria andLv6IsNotNull() {
            addCriterion("lv_6 is not null");
            return (Criteria) this;
        }

        public Criteria andLv6EqualTo(Integer value) {
            addCriterion("lv_6 =", value, "lv6");
            return (Criteria) this;
        }

        public Criteria andLv6NotEqualTo(Integer value) {
            addCriterion("lv_6 <>", value, "lv6");
            return (Criteria) this;
        }

        public Criteria andLv6GreaterThan(Integer value) {
            addCriterion("lv_6 >", value, "lv6");
            return (Criteria) this;
        }

        public Criteria andLv6GreaterThanOrEqualTo(Integer value) {
            addCriterion("lv_6 >=", value, "lv6");
            return (Criteria) this;
        }

        public Criteria andLv6LessThan(Integer value) {
            addCriterion("lv_6 <", value, "lv6");
            return (Criteria) this;
        }

        public Criteria andLv6LessThanOrEqualTo(Integer value) {
            addCriterion("lv_6 <=", value, "lv6");
            return (Criteria) this;
        }

        public Criteria andLv6In(List<Integer> values) {
            addCriterion("lv_6 in", values, "lv6");
            return (Criteria) this;
        }

        public Criteria andLv6NotIn(List<Integer> values) {
            addCriterion("lv_6 not in", values, "lv6");
            return (Criteria) this;
        }

        public Criteria andLv6Between(Integer value1, Integer value2) {
            addCriterion("lv_6 between", value1, value2, "lv6");
            return (Criteria) this;
        }

        public Criteria andLv6NotBetween(Integer value1, Integer value2) {
            addCriterion("lv_6 not between", value1, value2, "lv6");
            return (Criteria) this;
        }

        public Criteria andVScoreIsNull() {
            addCriterion("v_score is null");
            return (Criteria) this;
        }

        public Criteria andVScoreIsNotNull() {
            addCriterion("v_score is not null");
            return (Criteria) this;
        }

        public Criteria andVScoreEqualTo(Integer value) {
            addCriterion("v_score =", value, "vScore");
            return (Criteria) this;
        }

        public Criteria andVScoreNotEqualTo(Integer value) {
            addCriterion("v_score <>", value, "vScore");
            return (Criteria) this;
        }

        public Criteria andVScoreGreaterThan(Integer value) {
            addCriterion("v_score >", value, "vScore");
            return (Criteria) this;
        }

        public Criteria andVScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("v_score >=", value, "vScore");
            return (Criteria) this;
        }

        public Criteria andVScoreLessThan(Integer value) {
            addCriterion("v_score <", value, "vScore");
            return (Criteria) this;
        }

        public Criteria andVScoreLessThanOrEqualTo(Integer value) {
            addCriterion("v_score <=", value, "vScore");
            return (Criteria) this;
        }

        public Criteria andVScoreIn(List<Integer> values) {
            addCriterion("v_score in", values, "vScore");
            return (Criteria) this;
        }

        public Criteria andVScoreNotIn(List<Integer> values) {
            addCriterion("v_score not in", values, "vScore");
            return (Criteria) this;
        }

        public Criteria andVScoreBetween(Integer value1, Integer value2) {
            addCriterion("v_score between", value1, value2, "vScore");
            return (Criteria) this;
        }

        public Criteria andVScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("v_score not between", value1, value2, "vScore");
            return (Criteria) this;
        }

        public Criteria andIncChargeIsNull() {
            addCriterion("inc_charge is null");
            return (Criteria) this;
        }

        public Criteria andIncChargeIsNotNull() {
            addCriterion("inc_charge is not null");
            return (Criteria) this;
        }

        public Criteria andIncChargeEqualTo(Integer value) {
            addCriterion("inc_charge =", value, "incCharge");
            return (Criteria) this;
        }

        public Criteria andIncChargeNotEqualTo(Integer value) {
            addCriterion("inc_charge <>", value, "incCharge");
            return (Criteria) this;
        }

        public Criteria andIncChargeGreaterThan(Integer value) {
            addCriterion("inc_charge >", value, "incCharge");
            return (Criteria) this;
        }

        public Criteria andIncChargeGreaterThanOrEqualTo(Integer value) {
            addCriterion("inc_charge >=", value, "incCharge");
            return (Criteria) this;
        }

        public Criteria andIncChargeLessThan(Integer value) {
            addCriterion("inc_charge <", value, "incCharge");
            return (Criteria) this;
        }

        public Criteria andIncChargeLessThanOrEqualTo(Integer value) {
            addCriterion("inc_charge <=", value, "incCharge");
            return (Criteria) this;
        }

        public Criteria andIncChargeIn(List<Integer> values) {
            addCriterion("inc_charge in", values, "incCharge");
            return (Criteria) this;
        }

        public Criteria andIncChargeNotIn(List<Integer> values) {
            addCriterion("inc_charge not in", values, "incCharge");
            return (Criteria) this;
        }

        public Criteria andIncChargeBetween(Integer value1, Integer value2) {
            addCriterion("inc_charge between", value1, value2, "incCharge");
            return (Criteria) this;
        }

        public Criteria andIncChargeNotBetween(Integer value1, Integer value2) {
            addCriterion("inc_charge not between", value1, value2, "incCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeIsNull() {
            addCriterion("total_charge is null");
            return (Criteria) this;
        }

        public Criteria andTotalChargeIsNotNull() {
            addCriterion("total_charge is not null");
            return (Criteria) this;
        }

        public Criteria andTotalChargeEqualTo(Integer value) {
            addCriterion("total_charge =", value, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeNotEqualTo(Integer value) {
            addCriterion("total_charge <>", value, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeGreaterThan(Integer value) {
            addCriterion("total_charge >", value, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_charge >=", value, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeLessThan(Integer value) {
            addCriterion("total_charge <", value, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeLessThanOrEqualTo(Integer value) {
            addCriterion("total_charge <=", value, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeIn(List<Integer> values) {
            addCriterion("total_charge in", values, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeNotIn(List<Integer> values) {
            addCriterion("total_charge not in", values, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeBetween(Integer value1, Integer value2) {
            addCriterion("total_charge between", value1, value2, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andTotalChargeNotBetween(Integer value1, Integer value2) {
            addCriterion("total_charge not between", value1, value2, "totalCharge");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("`date` is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("`date` is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterionForJDBCDate("`date` =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("`date` <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterionForJDBCDate("`date` >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("`date` >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterionForJDBCDate("`date` <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("`date` <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterionForJDBCDate("`date` in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("`date` not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("`date` between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("`date` not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(boolean value) {
            addCriterion("is_deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(boolean value) {
            addCriterion("is_deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(boolean value) {
            addCriterion("is_deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(boolean value) {
            addCriterion("is_deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(boolean value) {
            addCriterion("is_deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(boolean value) {
            addCriterion("is_deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("is_deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("is_deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(boolean value1, boolean value2) {
            addCriterion("is_deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(boolean value1, boolean value2) {
            addCriterion("is_deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(Date value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(Date value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(Date value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(Date value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(Date value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<Date> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<Date> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(Date value1, Date value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(Date value1, Date value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table av_daily_charge
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}