package com.yanjinbin.model;

import java.io.Serializable;
import java.util.Date;

public class AvDailyChargeEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.id
     *
     * @mbg.generated
     */
    private Integer avDailyChargeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.av_id
     *
     * @mbg.generated
     */
    private Long avId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.tag_id
     *
     * @mbg.generated
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.is_original
     *
     * @mbg.generated
     */
    private Integer original;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.upload_time
     *
     * @mbg.generated
     */
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.danmaku_count
     *
     * @mbg.generated
     */
    private Integer danmakuCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.comment_count
     *
     * @mbg.generated
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.collect_count
     *
     * @mbg.generated
     */
    private Integer collectCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.coin_count
     *
     * @mbg.generated
     */
    private Integer coinCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.share_count
     *
     * @mbg.generated
     */
    private Integer shareCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.elec_pay_count
     *
     * @mbg.generated
     */
    private Integer elecPayCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.total_play_count
     *
     * @mbg.generated
     */
    private Integer totalPlayCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.web_play_count
     *
     * @mbg.generated
     */
    private Integer webPlayCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.app_play_count
     *
     * @mbg.generated
     */
    private Integer appPlayCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.h5_play_count
     *
     * @mbg.generated
     */
    private Integer h5PlayCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.lv_unknown
     *
     * @mbg.generated
     */
    private Integer lvUnknown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.lv_0
     *
     * @mbg.generated
     */
    private Integer lv0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.lv_1
     *
     * @mbg.generated
     */
    private Integer lv1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.lv_2
     *
     * @mbg.generated
     */
    private Integer lv2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.lv_3
     *
     * @mbg.generated
     */
    private Integer lv3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.lv_4
     *
     * @mbg.generated
     */
    private Integer lv4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.lv_5
     *
     * @mbg.generated
     */
    private Integer lv5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.lv_6
     *
     * @mbg.generated
     */
    private Integer lv6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.v_score
     *
     * @mbg.generated
     */
    private Integer vScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.inc_charge
     *
     * @mbg.generated
     */
    private Integer incCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.total_charge
     *
     * @mbg.generated
     */
    private Integer totalCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.is_deleted
     *
     * @mbg.generated
     */
    private boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_daily_charge.mtime
     *
     * @mbg.generated
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.id
     *
     * @return the value of av_daily_charge.id
     *
     * @mbg.generated
     */
    public Integer getAvDailyChargeId() {
        return avDailyChargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.id
     *
     * @param avDailyChargeId the value for av_daily_charge.id
     *
     * @mbg.generated
     */
    public void setAvDailyChargeId(Integer avDailyChargeId) {
        this.avDailyChargeId = avDailyChargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.av_id
     *
     * @return the value of av_daily_charge.av_id
     *
     * @mbg.generated
     */
    public Long getAvId() {
        return avId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.av_id
     *
     * @param avId the value for av_daily_charge.av_id
     *
     * @mbg.generated
     */
    public void setAvId(Long avId) {
        this.avId = avId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.mid
     *
     * @return the value of av_daily_charge.mid
     *
     * @mbg.generated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.mid
     *
     * @param mid the value for av_daily_charge.mid
     *
     * @mbg.generated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.tag_id
     *
     * @return the value of av_daily_charge.tag_id
     *
     * @mbg.generated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.tag_id
     *
     * @param tagId the value for av_daily_charge.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.is_original
     *
     * @return the value of av_daily_charge.is_original
     *
     * @mbg.generated
     */
    public Integer getOriginal() {
        return original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.is_original
     *
     * @param original the value for av_daily_charge.is_original
     *
     * @mbg.generated
     */
    public void setOriginal(Integer original) {
        this.original = original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.upload_time
     *
     * @return the value of av_daily_charge.upload_time
     *
     * @mbg.generated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.upload_time
     *
     * @param uploadTime the value for av_daily_charge.upload_time
     *
     * @mbg.generated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.danmaku_count
     *
     * @return the value of av_daily_charge.danmaku_count
     *
     * @mbg.generated
     */
    public Integer getDanmakuCount() {
        return danmakuCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.danmaku_count
     *
     * @param danmakuCount the value for av_daily_charge.danmaku_count
     *
     * @mbg.generated
     */
    public void setDanmakuCount(Integer danmakuCount) {
        this.danmakuCount = danmakuCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.comment_count
     *
     * @return the value of av_daily_charge.comment_count
     *
     * @mbg.generated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.comment_count
     *
     * @param commentCount the value for av_daily_charge.comment_count
     *
     * @mbg.generated
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.collect_count
     *
     * @return the value of av_daily_charge.collect_count
     *
     * @mbg.generated
     */
    public Integer getCollectCount() {
        return collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.collect_count
     *
     * @param collectCount the value for av_daily_charge.collect_count
     *
     * @mbg.generated
     */
    public void setCollectCount(Integer collectCount) {
        this.collectCount = collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.coin_count
     *
     * @return the value of av_daily_charge.coin_count
     *
     * @mbg.generated
     */
    public Integer getCoinCount() {
        return coinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.coin_count
     *
     * @param coinCount the value for av_daily_charge.coin_count
     *
     * @mbg.generated
     */
    public void setCoinCount(Integer coinCount) {
        this.coinCount = coinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.share_count
     *
     * @return the value of av_daily_charge.share_count
     *
     * @mbg.generated
     */
    public Integer getShareCount() {
        return shareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.share_count
     *
     * @param shareCount the value for av_daily_charge.share_count
     *
     * @mbg.generated
     */
    public void setShareCount(Integer shareCount) {
        this.shareCount = shareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.elec_pay_count
     *
     * @return the value of av_daily_charge.elec_pay_count
     *
     * @mbg.generated
     */
    public Integer getElecPayCount() {
        return elecPayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.elec_pay_count
     *
     * @param elecPayCount the value for av_daily_charge.elec_pay_count
     *
     * @mbg.generated
     */
    public void setElecPayCount(Integer elecPayCount) {
        this.elecPayCount = elecPayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.total_play_count
     *
     * @return the value of av_daily_charge.total_play_count
     *
     * @mbg.generated
     */
    public Integer getTotalPlayCount() {
        return totalPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.total_play_count
     *
     * @param totalPlayCount the value for av_daily_charge.total_play_count
     *
     * @mbg.generated
     */
    public void setTotalPlayCount(Integer totalPlayCount) {
        this.totalPlayCount = totalPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.web_play_count
     *
     * @return the value of av_daily_charge.web_play_count
     *
     * @mbg.generated
     */
    public Integer getWebPlayCount() {
        return webPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.web_play_count
     *
     * @param webPlayCount the value for av_daily_charge.web_play_count
     *
     * @mbg.generated
     */
    public void setWebPlayCount(Integer webPlayCount) {
        this.webPlayCount = webPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.app_play_count
     *
     * @return the value of av_daily_charge.app_play_count
     *
     * @mbg.generated
     */
    public Integer getAppPlayCount() {
        return appPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.app_play_count
     *
     * @param appPlayCount the value for av_daily_charge.app_play_count
     *
     * @mbg.generated
     */
    public void setAppPlayCount(Integer appPlayCount) {
        this.appPlayCount = appPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.h5_play_count
     *
     * @return the value of av_daily_charge.h5_play_count
     *
     * @mbg.generated
     */
    public Integer getH5PlayCount() {
        return h5PlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.h5_play_count
     *
     * @param h5PlayCount the value for av_daily_charge.h5_play_count
     *
     * @mbg.generated
     */
    public void setH5PlayCount(Integer h5PlayCount) {
        this.h5PlayCount = h5PlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.lv_unknown
     *
     * @return the value of av_daily_charge.lv_unknown
     *
     * @mbg.generated
     */
    public Integer getLvUnknown() {
        return lvUnknown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.lv_unknown
     *
     * @param lvUnknown the value for av_daily_charge.lv_unknown
     *
     * @mbg.generated
     */
    public void setLvUnknown(Integer lvUnknown) {
        this.lvUnknown = lvUnknown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.lv_0
     *
     * @return the value of av_daily_charge.lv_0
     *
     * @mbg.generated
     */
    public Integer getLv0() {
        return lv0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.lv_0
     *
     * @param lv0 the value for av_daily_charge.lv_0
     *
     * @mbg.generated
     */
    public void setLv0(Integer lv0) {
        this.lv0 = lv0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.lv_1
     *
     * @return the value of av_daily_charge.lv_1
     *
     * @mbg.generated
     */
    public Integer getLv1() {
        return lv1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.lv_1
     *
     * @param lv1 the value for av_daily_charge.lv_1
     *
     * @mbg.generated
     */
    public void setLv1(Integer lv1) {
        this.lv1 = lv1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.lv_2
     *
     * @return the value of av_daily_charge.lv_2
     *
     * @mbg.generated
     */
    public Integer getLv2() {
        return lv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.lv_2
     *
     * @param lv2 the value for av_daily_charge.lv_2
     *
     * @mbg.generated
     */
    public void setLv2(Integer lv2) {
        this.lv2 = lv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.lv_3
     *
     * @return the value of av_daily_charge.lv_3
     *
     * @mbg.generated
     */
    public Integer getLv3() {
        return lv3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.lv_3
     *
     * @param lv3 the value for av_daily_charge.lv_3
     *
     * @mbg.generated
     */
    public void setLv3(Integer lv3) {
        this.lv3 = lv3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.lv_4
     *
     * @return the value of av_daily_charge.lv_4
     *
     * @mbg.generated
     */
    public Integer getLv4() {
        return lv4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.lv_4
     *
     * @param lv4 the value for av_daily_charge.lv_4
     *
     * @mbg.generated
     */
    public void setLv4(Integer lv4) {
        this.lv4 = lv4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.lv_5
     *
     * @return the value of av_daily_charge.lv_5
     *
     * @mbg.generated
     */
    public Integer getLv5() {
        return lv5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.lv_5
     *
     * @param lv5 the value for av_daily_charge.lv_5
     *
     * @mbg.generated
     */
    public void setLv5(Integer lv5) {
        this.lv5 = lv5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.lv_6
     *
     * @return the value of av_daily_charge.lv_6
     *
     * @mbg.generated
     */
    public Integer getLv6() {
        return lv6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.lv_6
     *
     * @param lv6 the value for av_daily_charge.lv_6
     *
     * @mbg.generated
     */
    public void setLv6(Integer lv6) {
        this.lv6 = lv6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.v_score
     *
     * @return the value of av_daily_charge.v_score
     *
     * @mbg.generated
     */
    public Integer getvScore() {
        return vScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.v_score
     *
     * @param vScore the value for av_daily_charge.v_score
     *
     * @mbg.generated
     */
    public void setvScore(Integer vScore) {
        this.vScore = vScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.inc_charge
     *
     * @return the value of av_daily_charge.inc_charge
     *
     * @mbg.generated
     */
    public Integer getIncCharge() {
        return incCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.inc_charge
     *
     * @param incCharge the value for av_daily_charge.inc_charge
     *
     * @mbg.generated
     */
    public void setIncCharge(Integer incCharge) {
        this.incCharge = incCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.total_charge
     *
     * @return the value of av_daily_charge.total_charge
     *
     * @mbg.generated
     */
    public Integer getTotalCharge() {
        return totalCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.total_charge
     *
     * @param totalCharge the value for av_daily_charge.total_charge
     *
     * @mbg.generated
     */
    public void setTotalCharge(Integer totalCharge) {
        this.totalCharge = totalCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.date
     *
     * @return the value of av_daily_charge.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.date
     *
     * @param date the value for av_daily_charge.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.is_deleted
     *
     * @return the value of av_daily_charge.is_deleted
     *
     * @mbg.generated
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.is_deleted
     *
     * @param deleted the value for av_daily_charge.is_deleted
     *
     * @mbg.generated
     */
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.ctime
     *
     * @return the value of av_daily_charge.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.ctime
     *
     * @param ctime the value for av_daily_charge.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_daily_charge.mtime
     *
     * @return the value of av_daily_charge.mtime
     *
     * @mbg.generated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_daily_charge.mtime
     *
     * @param mtime the value for av_daily_charge.mtime
     *
     * @mbg.generated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_daily_charge
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", avDailyChargeId=").append(avDailyChargeId);
        sb.append(", avId=").append(avId);
        sb.append(", mid=").append(mid);
        sb.append(", tagId=").append(tagId);
        sb.append(", original=").append(original);
        sb.append(", uploadTime=").append(uploadTime);
        sb.append(", danmakuCount=").append(danmakuCount);
        sb.append(", commentCount=").append(commentCount);
        sb.append(", collectCount=").append(collectCount);
        sb.append(", coinCount=").append(coinCount);
        sb.append(", shareCount=").append(shareCount);
        sb.append(", elecPayCount=").append(elecPayCount);
        sb.append(", totalPlayCount=").append(totalPlayCount);
        sb.append(", webPlayCount=").append(webPlayCount);
        sb.append(", appPlayCount=").append(appPlayCount);
        sb.append(", h5PlayCount=").append(h5PlayCount);
        sb.append(", lvUnknown=").append(lvUnknown);
        sb.append(", lv0=").append(lv0);
        sb.append(", lv1=").append(lv1);
        sb.append(", lv2=").append(lv2);
        sb.append(", lv3=").append(lv3);
        sb.append(", lv4=").append(lv4);
        sb.append(", lv5=").append(lv5);
        sb.append(", lv6=").append(lv6);
        sb.append(", vScore=").append(vScore);
        sb.append(", incCharge=").append(incCharge);
        sb.append(", totalCharge=").append(totalCharge);
        sb.append(", date=").append(date);
        sb.append(", deleted=").append(deleted);
        sb.append(", ctime=").append(ctime);
        sb.append(", mtime=").append(mtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}